//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the mypack package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Request_QNAME = new QName("urn://egisso-ru/types/registers-request/1.0.1", "request");
    private final static QName _SovietPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "SovietPassport");
    private final static QName _Response_QNAME = new QName("urn://egisso-ru/types/registers-response/1.0.1", "response");
    private final static QName _MilitaryPassport2_QNAME = new QName("urn://egisso-ru/types/basic/1.0.7", "MilitaryPassport2");
    private final static QName _Form9Certificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "Form9Certificate");
    private final static QName _ResidencePermitRF2_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "ResidencePermitRF2");
    private final static QName _InternationalPassportRF2_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "InternationalPassportRF2");
    private final static QName _PassportRF2_QNAME = new QName("urn://egisso-ru/types/basic/1.0.7", "PassportRF2");
    private final static QName _BirthCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "BirthCertificate");
    private final static QName _PrimaryIdentityDocument_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "PrimaryIdentityDocument");
    private final static QName _ForeignPassport2_QNAME = new QName("urn://egisso-ru/types/basic/1.0.7", "ForeignPassport2");
    private final static QName _TemporaryIdentityCardRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "TemporaryIdentityCardRF");
    private final static QName _PassportRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "PassportRF");
    private final static QName _MilitaryPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "MilitaryPassport");
    private final static QName _ReleaseCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "ReleaseCertificate");
    private final static QName _DrivingLicenseRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "DrivingLicenseRF");
    private final static QName _AttachmentRef_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "AttachmentRef");
    private final static QName _TemporaryIdentityCardRF2_QNAME = new QName("urn://egisso-ru/types/basic/1.0.7", "TemporaryIdentityCardRF2");
    private final static QName _ForeignPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "ForeignPassport");
    private final static QName _BirthCertificate2_QNAME = new QName("urn://egisso-ru/types/basic/1.0.7", "BirthCertificate2");
    private final static QName _PassportLossCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "PassportLossCertificate");
    private final static QName _ResidencePermitRF_QNAME = new QName("urn://egisso-ru/types/basic/1.0.7", "ResidencePermitRF");
    private final static QName _SailorPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "SailorPassport");
    private final static QName _IdentityDocument_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "IdentityDocument");
    private final static QName _TExternalEventLifecycleRecordsRecoveryRecord_QNAME = new QName("urn://egisso-ru/types/registers-response/1.0.1", "recoveryRecord");
    private final static QName _TExternalEventLifecycleRecordsAnnulRecord_QNAME = new QName("urn://egisso-ru/types/registers-response/1.0.1", "annulRecord");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mypack
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TExternalEvent }
     *
     */
    public TExternalEvent createTExternalEvent() {
        return new TExternalEvent();
    }

    /**
     * Create an instance of {@link TRepresentativeRequestData }
     *
     */
    public TRepresentativeRequestData createTRepresentativeRequestData() {
        return new TRepresentativeRequestData();
    }

    /**
     * Create an instance of {@link TRequestData }
     *
     */
    public TRequestData createTRequestData() {
        return new TRequestData();
    }

    /**
     * Create an instance of {@link TRequestData.Rzp }
     *
     */
    public TRequestData.Rzp createTRequestDataRzp() {
        return new TRequestData.Rzp();
    }

    /**
     * Create an instance of {@link TRequestData.Rlirp }
     *
     */
    public TRequestData.Rlirp createTRequestDataRlirp() {
        return new TRequestData.Rlirp();
    }

    /**
     * Create an instance of {@link Response }
     *
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link TResponseData }
     *
     */
    public TResponseData createTResponseData() {
        return new TResponseData();
    }

    /**
     * Create an instance of {@link Request }
     *
     */
    public Request createRequest() {
        return new Request();
    }



    /**
     * Create an instance of {@link TClsVersion }
     *
     */
    public TClsVersion createTClsVersion() {
        return new TClsVersion();
    }

    /**
     * Create an instance of {@link TAddress }
     *
     */
    public TAddress createTAddress() {
        return new TAddress();
    }

    /**
     * Create an instance of {@link TError }
     *
     */
    public TError createTError() {
        return new TError();
    }


    /**
     * Create an instance of {@link TInternalEvent }
     *
     */
    public TInternalEvent createTInternalEvent() {
        return new TInternalEvent();
    }

    /**
     * Create an instance of {@link TAnnulRecoveryRecord }
     *
     */
    public TAnnulRecoveryRecord createTAnnulRecoveryRecord() {
        return new TAnnulRecoveryRecord();
    }

    /**
     * Create an instance of {@link TRegisterRecord }
     *
     */
    public TRegisterRecord createTRegisterRecord() {
        return new TRegisterRecord();
    }

    /**
     * Create an instance of {@link TDossierData }
     *
     */
    public TDossierData createTDossierData() {
        return new TDossierData();
    }

    /**
     * Create an instance of {@link TStatementData }
     *
     */
    public TStatementData createTStatementData() {
        return new TStatementData();
    }

    /**
     * Create an instance of {@link TUndefinedDocument }
     *
     */
    public TUndefinedDocument createTUndefinedDocument() {
        return new TUndefinedDocument();
    }

    /**
     * Create an instance of {@link TPerson }
     *
     */
    public TPerson createTPerson() {
        return new TPerson();
    }

    /**
     * Create an instance of {@link TPhysicalPerson }
     *
     */
    public TPhysicalPerson createTPhysicalPerson() {
        return new TPhysicalPerson();
    }

    /**
     * Create an instance of {@link TDefinedDocument }
     *
     */
    public TDefinedDocument createTDefinedDocument() {
        return new TDefinedDocument();
    }

    /**
     * Create an instance of {@link TInfoProvider }
     *
     */
    public TInfoProvider createTInfoProvider() {
        return new TInfoProvider();
    }

    /**
     * Create an instance of {@link TLegalPerson }
     *
     */
    public TLegalPerson createTLegalPerson() {
        return new TLegalPerson();
    }

    /**
     * Create an instance of {@link TPhysicalPersonWithRole }
     *
     */
    public TPhysicalPersonWithRole createTPhysicalPersonWithRole() {
        return new TPhysicalPersonWithRole();
    }

    /**
     * Create an instance of {@link TExternalEvent.LifecycleRecords }
     *
     */
    public TExternalEvent.LifecycleRecords createTExternalEventLifecycleRecords() {
        return new TExternalEvent.LifecycleRecords();
    }

    /**
     * Create an instance of {@link TRepresentativeRequestData.PhysicalPerson }
     *
     */
    public TRepresentativeRequestData.PhysicalPerson createTRepresentativeRequestDataPhysicalPerson() {
        return new TRepresentativeRequestData.PhysicalPerson();
    }

    /**
     * Create an instance of {@link TRepresentativeRequestData.LegalPerson }
     *
     */
    public TRepresentativeRequestData.LegalPerson createTRepresentativeRequestDataLegalPerson() {
        return new TRepresentativeRequestData.LegalPerson();
    }

    /**
     * Create an instance of {@link TRequestData.Rlid }
     *
     */
    public TRequestData.Rlid createTRequestDataRlid() {
        return new TRequestData.Rlid();
    }

    /**
     * Create an instance of {@link TRequestData.Rzp.RelationRequest }
     *
     */
    public TRequestData.Rzp.RelationRequest createTRequestDataRzpRelationRequest() {
        return new TRequestData.Rzp.RelationRequest();
    }

    /**
     * Create an instance of {@link TRequestData.Rlirp.ParentRequest }
     *
     */
    public TRequestData.Rlirp.ParentRequest createTRequestDataRlirpParentRequest() {
        return new TRequestData.Rlirp.ParentRequest();
    }

    /**
     * Create an instance of {@link TRequestData.Rlirp.ChildRequest }
     *
     */
    public TRequestData.Rlirp.ChildRequest createTRequestDataRlirpChildRequest() {
        return new TRequestData.Rlirp.ChildRequest();
    }

    /**
     * Create an instance of {@link TRequestData.Rlirp.ParentChildRequest }
     *
     */
    public TRequestData.Rlirp.ParentChildRequest createTRequestDataRlirpParentChildRequest() {
        return new TRequestData.Rlirp.ParentChildRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRequestData }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn://egisso-ru/types/registers-request/1.0.1", name = "request")
    public JAXBElement<TRequestData> createRequest(TRequestData value) {
        return new JAXBElement<TRequestData>(_Request_QNAME, TRequestData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAnnulRecoveryRecord }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn://egisso-ru/types/registers-response/1.0.1", name = "recoveryRecord", scope = TExternalEvent.LifecycleRecords.class)
    public JAXBElement<TAnnulRecoveryRecord> createTExternalEventLifecycleRecordsRecoveryRecord(TAnnulRecoveryRecord value) {
        return new JAXBElement<TAnnulRecoveryRecord>(_TExternalEventLifecycleRecordsRecoveryRecord_QNAME, TAnnulRecoveryRecord.class, TExternalEvent.LifecycleRecords.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAnnulRecoveryRecord }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn://egisso-ru/types/registers-response/1.0.1", name = "annulRecord", scope = TExternalEvent.LifecycleRecords.class)
    public JAXBElement<TAnnulRecoveryRecord> createTExternalEventLifecycleRecordsAnnulRecord(TAnnulRecoveryRecord value) {
        return new JAXBElement<TAnnulRecoveryRecord>(_TExternalEventLifecycleRecordsAnnulRecord_QNAME, TAnnulRecoveryRecord.class, TExternalEvent.LifecycleRecords.class, value);
    }

}
