//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn://egisso-ru/types/registers-response/1.0.1}response"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response"
})
@XmlRootElement(name = "response", namespace = "urn://egisso-ru/msg/10.26.I/1.0.1")
public class Response {

    @XmlElement(namespace = "urn://egisso-ru/types/registers-response/1.0.1", required = true)
    protected TResponseData response;

    /**
     ****************************************************************************************************
     Вид сведений СМЭВ: «10.26.I ЗАПРОС В ЕГИССО НА ПОЛУЧЕНИЕ СВЕДЕНИЙ ИЗ РЕЕСТРА ЛИЦ, СВЯЗАННЫХ С ИЗМЕНЕНИЕМ РОДИТЕЛЬСКИХ ПРАВ, РЕЕСТРА ЛИЦ С ИЗМЕНЕННОЙ ДЕЕСПОСОБНОСТЬЮ И РЕЕСТРА ЗАКОННЫХ ПРЕДСТАВИТЕЛЕЙ»
     ****************************************************************************************************


     * @return
     *     possible object is
     *     {@link TResponseData }
     *
     */
    public TResponseData getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     *
     * @param value
     *     allowed object is
     *     {@link TResponseData }
     *
     */
    public void setResponse(TResponseData value) {
        this.response = value;
    }

}
