//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *
 *         ��� ������: �����
 *
 *
 * <p>Java class for tAddress complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OKSMCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d{3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PostIndex" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}PostalCodeRFType" minOccurs="0"/>
 *         &lt;element name="Region" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-100" minOccurs="0"/>
 *         &lt;element name="District" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-100" minOccurs="0"/>
 *         &lt;element name="City" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-100" minOccurs="0"/>
 *         &lt;element name="Street" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-100" minOccurs="0"/>
 *         &lt;element name="House" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-10" minOccurs="0"/>
 *         &lt;element name="Housing" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-10" minOccurs="0"/>
 *         &lt;element name="Apartment" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-10" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAddress", namespace = "urn://egisso-ru/types/basic/1.0.7", propOrder = {
    "oksmCode",
    "postIndex",
    "region",
    "district",
    "city",
    "street",
    "house",
    "housing",
    "apartment"
})
public class TAddress {

    @XmlElement(name = "OKSMCode", required = true)
    protected String oksmCode;
    @XmlElement(name = "PostIndex")
    protected String postIndex;
    @XmlElement(name = "Region")
    protected String region;
    @XmlElement(name = "District")
    protected String district;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "Street")
    protected String street;
    @XmlElement(name = "House")
    protected String house;
    @XmlElement(name = "Housing")
    protected String housing;
    @XmlElement(name = "Apartment")
    protected String apartment;

    /**
     * Gets the value of the oksmCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOKSMCode() {
        return oksmCode;
    }

    /**
     * Sets the value of the oksmCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOKSMCode(String value) {
        this.oksmCode = value;
    }

    /**
     * Gets the value of the postIndex property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPostIndex() {
        return postIndex;
    }

    /**
     * Sets the value of the postIndex property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPostIndex(String value) {
        this.postIndex = value;
    }

    /**
     * Gets the value of the region property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the district property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDistrict(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the city property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the street property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the house property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHouse() {
        return house;
    }

    /**
     * Sets the value of the house property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHouse(String value) {
        this.house = value;
    }

    /**
     * Gets the value of the housing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHousing() {
        return housing;
    }

    /**
     * Sets the value of the housing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHousing(String value) {
        this.housing = value;
    }

    /**
     * Gets the value of the apartment property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getApartment() {
        return apartment;
    }

    /**
     * Sets the value of the apartment property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setApartment(String value) {
        this.apartment = value;
    }

}
