//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * ��� ������ ���� ������ �� ������������� ��� �������������� ������������ ������� (��������)
 *
 * <p>Java class for tAnnulRecoveryRecord complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tAnnulRecoveryRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="reasonDocument" type="{urn://egisso-ru/types/registers/1.0.1}tUndefinedDocument"/>
 *         &lt;element name="infoProvider" type="{urn://egisso-ru/types/registers/1.0.1}tInfoProvider"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAnnulRecoveryRecord", namespace = "urn://egisso-ru/types/registers-response/1.0.1", propOrder = {
    "effectiveDate",
    "reasonDocument",
    "infoProvider"
})
public class TAnnulRecoveryRecord {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(required = true)
    protected TUndefinedDocument reasonDocument;
    @XmlElement(required = true)
    protected TInfoProvider infoProvider;

    /**
     * Gets the value of the effectiveDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the reasonDocument property.
     *
     * @return
     *     possible object is
     *     {@link TUndefinedDocument }
     *
     */
    public TUndefinedDocument getReasonDocument() {
        return reasonDocument;
    }

    /**
     * Sets the value of the reasonDocument property.
     *
     * @param value
     *     allowed object is
     *     {@link TUndefinedDocument }
     *
     */
    public void setReasonDocument(TUndefinedDocument value) {
        this.reasonDocument = value;
    }

    /**
     * Gets the value of the infoProvider property.
     *
     * @return
     *     possible object is
     *     {@link TInfoProvider }
     *
     */
    public TInfoProvider getInfoProvider() {
        return infoProvider;
    }

    /**
     * Sets the value of the infoProvider property.
     *
     * @param value
     *     allowed object is
     *     {@link TInfoProvider }
     *
     */
    public void setInfoProvider(TInfoProvider value) {
        this.infoProvider = value;
    }

}
