//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ��� ������ � ���������� ����������
 *
 * <p>Java class for tInfoProvider complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tInfoProvider">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{urn://egisso-ru/types/basic/1.0.7}string-1000"/>
 *         &lt;element name="inn" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}LegalPersonINNType"/>
 *         &lt;element name="ogrn" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}OGRNCompanyType"/>
 *         &lt;element name="codeParticipant" type="{urn://egisso-ru/types/basic/1.0.7}tParticipantCode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tInfoProvider", namespace = "urn://egisso-ru/types/registers/1.0.1", propOrder = {
    "name",
    "inn",
    "ogrn",
    "codeParticipant"
})
public class TInfoProvider {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String inn;
    @XmlElement(required = true)
    protected String ogrn;
    @XmlElement(required = true)
    protected String codeParticipant;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the inn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInn() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInn(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the ogrn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOgrn() {
        return ogrn;
    }

    /**
     * Sets the value of the ogrn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOgrn(String value) {
        this.ogrn = value;
    }

    /**
     * Gets the value of the codeParticipant property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodeParticipant() {
        return codeParticipant;
    }

    /**
     * Sets the value of the codeParticipant property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodeParticipant(String value) {
        this.codeParticipant = value;
    }

}
