//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * ��� ������ �� ����������� ������� ������������ ������� (��������), ������� ���� ��������������� ������
 *
 * <p>Java class for tInternalEvent complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tInternalEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codeEventType" type="{urn://egisso-ru/types/registers/1.0.1}tEventTypeCode"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="reasonDocument" type="{urn://egisso-ru/types/registers/1.0.1}tUndefinedDocument" minOccurs="0"/>
 *         &lt;element name="comment" type="{urn://egisso-ru/types/basic/1.0.7}string-1000" minOccurs="0"/>
 *         &lt;element name="person" type="{urn://egisso-ru/types/registers/1.0.1}tPerson" maxOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tInternalEvent", namespace = "urn://egisso-ru/types/registers-response/1.0.1", propOrder = {
    "codeEventType",
    "createDate",
    "effectiveDate",
    "reasonDocument",
    "comment",
    "person"
})
public class TInternalEvent {

    @XmlElement(required = true)
    protected String codeEventType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    protected TUndefinedDocument reasonDocument;
    protected String comment;
    @XmlElement(required = true)
    protected List<TPerson> person;

    /**
     * Gets the value of the codeEventType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodeEventType() {
        return codeEventType;
    }

    /**
     * Sets the value of the codeEventType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodeEventType(String value) {
        this.codeEventType = value;
    }

    /**
     * Gets the value of the createDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the reasonDocument property.
     *
     * @return
     *     possible object is
     *     {@link TUndefinedDocument }
     *
     */
    public TUndefinedDocument getReasonDocument() {
        return reasonDocument;
    }

    /**
     * Sets the value of the reasonDocument property.
     *
     * @param value
     *     allowed object is
     *     {@link TUndefinedDocument }
     *
     */
    public void setReasonDocument(TUndefinedDocument value) {
        this.reasonDocument = value;
    }

    /**
     * Gets the value of the comment property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the person property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the person property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerson().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TPerson }
     *
     *
     */
    public List<TPerson> getPerson() {
        if (person == null) {
            person = new ArrayList<TPerson>();
        }
        return this.person;
    }

}
