//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ��� ������ ������������ ����
 *
 * <p>Java class for tLegalPerson complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tLegalPerson">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="representative" type="{urn://egisso-ru/types/registers/1.0.1}tPhysicalPerson"/>
 *       &lt;/sequence>
 *       &lt;attribute name="codeRoleType" use="required" type="{urn://egisso-ru/types/registers/1.0.1}tRoleTypeCode" />
 *       &lt;attribute name="name" use="required" type="{urn://egisso-ru/types/basic/1.0.7}string-1000" />
 *       &lt;attribute name="inn" use="required" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}LegalPersonINNType" />
 *       &lt;attribute name="ogrn" use="required" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}OGRNCompanyType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tLegalPerson", namespace = "urn://egisso-ru/types/registers/1.0.1", propOrder = {
    "representative"
})
public class TLegalPerson {

    @XmlElement(required = true)
    protected TPhysicalPerson representative;
    @XmlAttribute(name = "codeRoleType", required = true)
    protected String codeRoleType;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "inn", required = true)
    protected String inn;
    @XmlAttribute(name = "ogrn", required = true)
    protected String ogrn;

    /**
     * Gets the value of the representative property.
     *
     * @return
     *     possible object is
     *     {@link TPhysicalPerson }
     *
     */
    public TPhysicalPerson getRepresentative() {
        return representative;
    }

    /**
     * Sets the value of the representative property.
     *
     * @param value
     *     allowed object is
     *     {@link TPhysicalPerson }
     *
     */
    public void setRepresentative(TPhysicalPerson value) {
        this.representative = value;
    }

    /**
     * Gets the value of the codeRoleType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodeRoleType() {
        return codeRoleType;
    }

    /**
     * Sets the value of the codeRoleType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodeRoleType(String value) {
        this.codeRoleType = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the inn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInn() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInn(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the ogrn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOgrn() {
        return ogrn;
    }

    /**
     * Sets the value of the ogrn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOgrn(String value) {
        this.ogrn = value;
    }

}
