//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import smev.ElementServices.Other.GenderType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * ��� ������ ����������� ����
 *
 * <p>Java class for tPhysicalPerson complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tPhysicalPerson">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="snils" use="required" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType" />
 *       &lt;attribute name="lastName" use="required" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-100" />
 *       &lt;attribute name="firstName" use="required" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-100" />
 *       &lt;attribute name="middleName" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-100" />
 *       &lt;attribute name="gender" use="required" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}GenderType" />
 *       &lt;attribute name="citizenshipCode" use="required" type="{urn://egisso-ru/types/basic/1.0.7}tOKSMCode" />
 *       &lt;attribute name="birthDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPhysicalPerson", namespace = "urn://egisso-ru/types/registers/1.0.1")
@XmlSeeAlso({
    TPhysicalPersonWithRole.class
})
public class TPhysicalPerson {

    @XmlAttribute(name = "snils", required = true)
    protected String snils;
    @XmlAttribute(name = "lastName", required = true)
    protected String lastName;
    @XmlAttribute(name = "firstName", required = true)
    protected String firstName;
    @XmlAttribute(name = "middleName")
    protected String middleName;
    @XmlAttribute(name = "gender", required = true)
    protected GenderType gender;
    @XmlAttribute(name = "citizenshipCode", required = true)
    protected String citizenshipCode;
    @XmlAttribute(name = "birthDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;

    /**
     * Gets the value of the snils property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSnils() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSnils(String value) {
        this.snils = value;
    }

    /**
     * Gets the value of the lastName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the gender property.
     *
     * @return
     *     possible object is
     *     {@link GenderType }
     *
     */
    public GenderType getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     *
     * @param value
     *     allowed object is
     *     {@link GenderType }
     *
     */
    public void setGender(GenderType value) {
        this.gender = value;
    }

    /**
     * Gets the value of the citizenshipCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCitizenshipCode() {
        return citizenshipCode;
    }

    /**
     * Sets the value of the citizenshipCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCitizenshipCode(String value) {
        this.citizenshipCode = value;
    }

    /**
     * Gets the value of the birthDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

}
