//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ��� ������ ������������ �������� � ������� ���������� ���������� � �������
 *
 * <p>Java class for tRegisterRecord complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tRegisterRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codePresenceStatus" type="{urn://egisso-ru/types/registers/1.0.1}tPresenceStatusCode"/>
 *         &lt;element name="legalStatus" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-500" minOccurs="0"/>
 *         &lt;element name="dossierData" type="{urn://egisso-ru/types/registers-response/1.0.1}tDossierData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRegisterRecord", namespace = "urn://egisso-ru/types/registers-response/1.0.1", propOrder = {
    "codePresenceStatus",
    "legalStatus",
    "dossierData"
})
public class TRegisterRecord {

    @XmlElement(required = true)
    protected String codePresenceStatus;
    protected String legalStatus;
    protected TDossierData dossierData;

    /**
     * Gets the value of the codePresenceStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodePresenceStatus() {
        return codePresenceStatus;
    }

    /**
     * Sets the value of the codePresenceStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodePresenceStatus(String value) {
        this.codePresenceStatus = value;
    }

    /**
     * Gets the value of the legalStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLegalStatus() {
        return legalStatus;
    }

    /**
     * Sets the value of the legalStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLegalStatus(String value) {
        this.legalStatus = value;
    }

    /**
     * Gets the value of the dossierData property.
     *
     * @return
     *     possible object is
     *     {@link TDossierData }
     *
     */
    public TDossierData getDossierData() {
        return dossierData;
    }

    /**
     * Sets the value of the dossierData property.
     *
     * @param value
     *     allowed object is
     *     {@link TDossierData }
     *
     */
    public void setDossierData(TDossierData value) {
        this.dossierData = value;
    }

}
