//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ����� ������ ������� �� �������������
 *
 * <p>Java class for tRepresentativeRequestData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tRepresentativeRequestData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="physicalPerson">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="legalPerson">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *                   &lt;element name="inn" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}LegalPersonINNType"/>
 *                   &lt;element name="ogrn" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}OGRNCompanyType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRepresentativeRequestData", namespace = "urn://egisso-ru/types/registers-request/1.0.1", propOrder = {
    "physicalPerson",
    "legalPerson"
})
public class TRepresentativeRequestData {

    protected TRepresentativeRequestData.PhysicalPerson physicalPerson;
    protected TRepresentativeRequestData.LegalPerson legalPerson;

    /**
     * Gets the value of the physicalPerson property.
     *
     * @return
     *     possible object is
     *     {@link TRepresentativeRequestData.PhysicalPerson }
     *
     */
    public TRepresentativeRequestData.PhysicalPerson getPhysicalPerson() {
        return physicalPerson;
    }

    /**
     * Sets the value of the physicalPerson property.
     *
     * @param value
     *     allowed object is
     *     {@link TRepresentativeRequestData.PhysicalPerson }
     *
     */
    public void setPhysicalPerson(TRepresentativeRequestData.PhysicalPerson value) {
        this.physicalPerson = value;
    }

    /**
     * Gets the value of the legalPerson property.
     *
     * @return
     *     possible object is
     *     {@link TRepresentativeRequestData.LegalPerson }
     *
     */
    public TRepresentativeRequestData.LegalPerson getLegalPerson() {
        return legalPerson;
    }

    /**
     * Sets the value of the legalPerson property.
     *
     * @param value
     *     allowed object is
     *     {@link TRepresentativeRequestData.LegalPerson }
     *
     */
    public void setLegalPerson(TRepresentativeRequestData.LegalPerson value) {
        this.legalPerson = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
     *         &lt;element name="inn" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}LegalPersonINNType"/>
     *         &lt;element name="ogrn" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}OGRNCompanyType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "snils",
        "inn",
        "ogrn"
    })
    public static class LegalPerson {

        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1")
        protected String snils;
        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1")
        protected String inn;
        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1")
        protected String ogrn;

        /**
         * Gets the value of the snils property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSnils() {
            return snils;
        }

        /**
         * Sets the value of the snils property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSnils(String value) {
            this.snils = value;
        }

        /**
         * Gets the value of the inn property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getInn() {
            return inn;
        }

        /**
         * Sets the value of the inn property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setInn(String value) {
            this.inn = value;
        }

        /**
         * Gets the value of the ogrn property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOgrn() {
            return ogrn;
        }

        /**
         * Sets the value of the ogrn property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOgrn(String value) {
            this.ogrn = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "snils"
    })
    public static class PhysicalPerson {

        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1", required = true)
        protected String snils;

        /**
         * Gets the value of the snils property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSnils() {
            return snils;
        }

        /**
         * Sets the value of the snils property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSnils(String value) {
            this.snils = value;
        }

    }

}
