//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.20 at 02:10:35 PM MSK
//


package smev.ElementServices.Egisso.Registers;

import smev.dao.EntitySmev.BusinessMessageEntity;
import smev.Send.TypeBussines;
import smev.Service.Impl.BusinessServiceImpl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * ��� ������: ������������� �������� � ��������� ��� ���������� ���� ��� ��������� ��� �� ������� ���, ��������� � ���������� ������������ ����, ������� ��� � ���������� ��������������� � ������� �������� ��������������
 *
 * <p>Java class for tRequestData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tRequestData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rlirp" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="parentRequest">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="childRequest">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="parentChildRequest">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="parentSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *                             &lt;element name="childSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rlid" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rzp" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="representativeRequest" type="{urn://egisso-ru/types/registers-request/1.0.1}tRepresentativeRequestData"/>
 *                   &lt;element name="representedPersonRequestSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *                   &lt;element name="relationRequest">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="representative" type="{urn://egisso-ru/types/registers-request/1.0.1}tRepresentativeRequestData"/>
 *                             &lt;element name="representedPersonSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="statusOnDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="withDossier" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRequestData", namespace = "urn://egisso-ru/types/registers-request/1.0.1", propOrder = {
    "rlirp",
    "rlid",
    "rzp",
    "statusOnDate",
    "withDossier"
})
public class TRequestData implements TypeBussines {

    protected TRequestData.Rlirp rlirp;
    protected TRequestData.Rlid rlid;
    protected TRequestData.Rzp rzp;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar statusOnDate;
    @XmlElement(defaultValue = "true")
    protected Boolean withDossier;

    /**
     * Gets the value of the rlirp property.
     *
     * @return
     *     possible object is
     *     {@link TRequestData.Rlirp }
     *
     */
    public TRequestData.Rlirp getRlirp() {
        return rlirp;
    }

    /**
     * Sets the value of the rlirp property.
     *
     * @param value
     *     allowed object is
     *     {@link TRequestData.Rlirp }
     *
     */
    public void setRlirp(TRequestData.Rlirp value) {
        this.rlirp = value;
    }

    /**
     * Gets the value of the rlid property.
     *
     * @return
     *     possible object is
     *     {@link TRequestData.Rlid }
     *
     */
    public TRequestData.Rlid getRlid() {
        return rlid;
    }

    /**
     * Sets the value of the rlid property.
     *
     * @param value
     *     allowed object is
     *     {@link TRequestData.Rlid }
     *
     */
    public void setRlid(TRequestData.Rlid value) {
        this.rlid = value;
    }

    /**
     * Gets the value of the rzp property.
     *
     * @return
     *     possible object is
     *     {@link TRequestData.Rzp }
     *
     */
    public TRequestData.Rzp getRzp() {
        return rzp;
    }

    /**
     * Sets the value of the rzp property.
     *
     * @param value
     *     allowed object is
     *     {@link TRequestData.Rzp }
     *
     */
    public void setRzp(TRequestData.Rzp value) {
        this.rzp = value;
    }

    /**
     * Gets the value of the statusOnDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getStatusOnDate() {
        return statusOnDate;
    }

    /**
     * Sets the value of the statusOnDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setStatusOnDate(XMLGregorianCalendar value) {
        this.statusOnDate = value;
    }

    /**
     * Gets the value of the withDossier property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isWithDossier() {
        return withDossier;
    }

    /**
     * Sets the value of the withDossier property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setWithDossier(Boolean value) {
        this.withDossier = value;
    }

    @Override
    public Object tt(BusinessServiceImpl businessService, BusinessMessageEntity messageEntity) {
        return null;
    }

    @Override
    public String fillObj(BusinessServiceImpl businessService, BusinessMessageEntity messageEntity) {
        return null;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "snils"
    })
    public static class Rlid {

        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1", required = true)
        protected String snils;

        /**
         * Gets the value of the snils property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSnils() {
            return snils;
        }

        /**
         * Sets the value of the snils property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSnils(String value) {
            this.snils = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="parentRequest">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="childRequest">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="parentChildRequest">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="parentSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
     *                   &lt;element name="childSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parentRequest",
        "childRequest",
        "parentChildRequest"
    })
    public static class Rlirp {

        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1")
        protected TRequestData.Rlirp.ParentRequest parentRequest;
        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1")
        protected TRequestData.Rlirp.ChildRequest childRequest;
        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1")
        protected TRequestData.Rlirp.ParentChildRequest parentChildRequest;

        /**
         * Gets the value of the parentRequest property.
         *
         * @return
         *     possible object is
         *     {@link TRequestData.Rlirp.ParentRequest }
         *
         */
        public TRequestData.Rlirp.ParentRequest getParentRequest() {
            return parentRequest;
        }

        /**
         * Sets the value of the parentRequest property.
         *
         * @param value
         *     allowed object is
         *     {@link TRequestData.Rlirp.ParentRequest }
         *
         */
        public void setParentRequest(TRequestData.Rlirp.ParentRequest value) {
            this.parentRequest = value;
        }

        /**
         * Gets the value of the childRequest property.
         *
         * @return
         *     possible object is
         *     {@link TRequestData.Rlirp.ChildRequest }
         *
         */
        public TRequestData.Rlirp.ChildRequest getChildRequest() {
            return childRequest;
        }

        /**
         * Sets the value of the childRequest property.
         *
         * @param value
         *     allowed object is
         *     {@link TRequestData.Rlirp.ChildRequest }
         *
         */
        public void setChildRequest(TRequestData.Rlirp.ChildRequest value) {
            this.childRequest = value;
        }

        /**
         * Gets the value of the parentChildRequest property.
         *
         * @return
         *     possible object is
         *     {@link TRequestData.Rlirp.ParentChildRequest }
         *
         */
        public TRequestData.Rlirp.ParentChildRequest getParentChildRequest() {
            return parentChildRequest;
        }

        /**
         * Sets the value of the parentChildRequest property.
         *
         * @param value
         *     allowed object is
         *     {@link TRequestData.Rlirp.ParentChildRequest }
         *
         */
        public void setParentChildRequest(TRequestData.Rlirp.ParentChildRequest value) {
            this.parentChildRequest = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "snils"
        })
        public static class ChildRequest {

            @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1", required = true)
            protected String snils;

            /**
             * Gets the value of the snils property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getSnils() {
                return snils;
            }

            /**
             * Sets the value of the snils property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setSnils(String value) {
                this.snils = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="parentSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
         *         &lt;element name="childSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "parentSnils",
            "childSnils"
        })
        public static class ParentChildRequest {

            @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1", required = true)
            protected String parentSnils;
            @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1", required = true)
            protected String childSnils;

            /**
             * Gets the value of the parentSnils property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getParentSnils() {
                return parentSnils;
            }

            /**
             * Sets the value of the parentSnils property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setParentSnils(String value) {
                this.parentSnils = value;
            }

            /**
             * Gets the value of the childSnils property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getChildSnils() {
                return childSnils;
            }

            /**
             * Sets the value of the childSnils property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setChildSnils(String value) {
                this.childSnils = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "snils"
        })
        public static class ParentRequest {

            @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1", required = true)
            protected String snils;

            /**
             * Gets the value of the snils property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getSnils() {
                return snils;
            }

            /**
             * Sets the value of the snils property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setSnils(String value) {
                this.snils = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="representativeRequest" type="{urn://egisso-ru/types/registers-request/1.0.1}tRepresentativeRequestData"/>
     *         &lt;element name="representedPersonRequestSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
     *         &lt;element name="relationRequest">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="representative" type="{urn://egisso-ru/types/registers-request/1.0.1}tRepresentativeRequestData"/>
     *                   &lt;element name="representedPersonSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "representativeRequest",
        "representedPersonRequestSnils",
        "relationRequest"
    })
    public static class Rzp {

        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1")
        protected TRepresentativeRequestData representativeRequest;
        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1")
        protected String representedPersonRequestSnils;
        @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1")
        protected TRequestData.Rzp.RelationRequest relationRequest;

        /**
         * Gets the value of the representativeRequest property.
         *
         * @return
         *     possible object is
         *     {@link TRepresentativeRequestData }
         *
         */
        public TRepresentativeRequestData getRepresentativeRequest() {
            return representativeRequest;
        }

        /**
         * Sets the value of the representativeRequest property.
         *
         * @param value
         *     allowed object is
         *     {@link TRepresentativeRequestData }
         *
         */
        public void setRepresentativeRequest(TRepresentativeRequestData value) {
            this.representativeRequest = value;
        }

        /**
         * Gets the value of the representedPersonRequestSnils property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRepresentedPersonRequestSnils() {
            return representedPersonRequestSnils;
        }

        /**
         * Sets the value of the representedPersonRequestSnils property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRepresentedPersonRequestSnils(String value) {
            this.representedPersonRequestSnils = value;
        }

        /**
         * Gets the value of the relationRequest property.
         *
         * @return
         *     possible object is
         *     {@link TRequestData.Rzp.RelationRequest }
         *
         */
        public TRequestData.Rzp.RelationRequest getRelationRequest() {
            return relationRequest;
        }

        /**
         * Sets the value of the relationRequest property.
         *
         * @param value
         *     allowed object is
         *     {@link TRequestData.Rzp.RelationRequest }
         *
         */
        public void setRelationRequest(TRequestData.Rzp.RelationRequest value) {
            this.relationRequest = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="representative" type="{urn://egisso-ru/types/registers-request/1.0.1}tRepresentativeRequestData"/>
         *         &lt;element name="representedPersonSnils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "representative",
            "representedPersonSnils"
        })
        public static class RelationRequest {

            @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1", required = true)
            protected TRepresentativeRequestData representative;
            @XmlElement(namespace = "urn://egisso-ru/types/registers-request/1.0.1", required = true)
            protected String representedPersonSnils;

            /**
             * Gets the value of the representative property.
             *
             * @return
             *     possible object is
             *     {@link TRepresentativeRequestData }
             *
             */
            public TRepresentativeRequestData getRepresentative() {
                return representative;
            }

            /**
             * Sets the value of the representative property.
             *
             * @param value
             *     allowed object is
             *     {@link TRepresentativeRequestData }
             *
             */
            public void setRepresentative(TRepresentativeRequestData value) {
                this.representative = value;
            }

            /**
             * Gets the value of the representedPersonSnils property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getRepresentedPersonSnils() {
                return representedPersonSnils;
            }

            /**
             * Sets the value of the representedPersonSnils property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setRepresentedPersonSnils(String value) {
                this.representedPersonSnils = value;
            }

        }

    }

}
