package smev.ElementServices.fault;



import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory
{
/* 27 */   private static final QName _ValidationFault_QNAME = new QName("urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults", "ValidationFault");
/* 28 */   private static final QName _SystemFault_QNAME = new QName("urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults", "SystemFault");
/* 29 */   private static final QName _SyncFault_QNAME = new QName("urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults", "SyncFault");












  public ValidationFault createValidationFault() {
/* 43 */     return new ValidationFault();
  }





  public SystemFault createSystemFault() {
/* 51 */     return new SystemFault();
  }





  public SyncFault createSyncFault() {
/* 59 */     return new SyncFault();
  }





  public Fault createFault() {
/* 67 */     return new Fault();
  }





  @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults", name = "ValidationFault")
  public JAXBElement<ValidationFault> createValidationFault(ValidationFault value) {
/* 76 */     return new JAXBElement<>(_ValidationFault_QNAME, ValidationFault.class, null, value);
  }





  @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults", name = "SystemFault")
  public JAXBElement<SystemFault> createSystemFault(SystemFault value) {
/* 85 */     return new JAXBElement<>(_SystemFault_QNAME, SystemFault.class, null, value);
  }





  @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults", name = "SyncFault")
  public JAXBElement<SyncFault> createSyncFault(SyncFault value) {
/* 94 */     return new JAXBElement<>(_SyncFault_QNAME, SyncFault.class, null, value);
  }
}


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\fault\ObjectFactory.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
