//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.04 at 01:57:44 PM MSK
//


package smev.ElementServices.Rosreestr;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttachmentRequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AttachmentRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="AttachmentFSLink" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *           &lt;element name="IsMTOMAttachmentContent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;/choice>
 *         &lt;element name="RequestDescription" type="{urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2}TValidatedStructuredAttachmentFormat"/>
 *         &lt;element name="Statement" type="{urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2}TValidatedStructuredAttachmentFormat" maxOccurs="unbounded"/>
 *         &lt;element name="File" type="{urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2}TStructuredAttachmentFormat" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttachmentRequestType", namespace = "urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2", propOrder = {
    "attachmentFSLink",
    "isMTOMAttachmentContent",
    "requestDescription",
    "statement",
    "file"
})
@Data
public class AttachmentRequestType {

    @XmlElement(name = "AttachmentFSLink")
    protected Boolean attachmentFSLink;

    @XmlElement(name = "IsMTOMAttachmentContent", namespace = "urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2")
    protected Boolean isMTOMAttachmentContent;

    @XmlElement(name = "RequestDescription", namespace = "urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2", required = true)
    protected TValidatedStructuredAttachmentFormat requestDescription;

    @XmlElement(name = "Statement", namespace = "urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2",required = true)
    protected List<TValidatedStructuredAttachmentFormat> statement;

    @XmlElement(name = "File", namespace = "urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2")
    protected List<TStructuredAttachmentFormat> file;


}
