//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DDataReceiveForm.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DDataReceiveForm">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="paper"/>
 *     &lt;enumeration value="electronic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "DDataReceiveForm", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons")
@XmlEnum
public enum DDataReceiveForm {


    /**
     * � �������� ����
     *
     */
    @XmlEnumValue("paper")
    PAPER("paper"),

    /**
     * � ����������� ����
     *
     */
    @XmlEnumValue("electronic")
    ELECTRONIC("electronic");
    private final String value;

    DDataReceiveForm(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DDataReceiveForm fromValue(String v) {
        for (DDataReceiveForm c: DDataReceiveForm.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
