//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ �������� ����������� � ������ ���������
 *
 * <p>Java class for TAcceptActionNotification complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TAcceptActionNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="postAddress" type="{http://rosreestr.ru/services/v0.1/commons/Address}TAddress"/>
 *         &lt;element name="eMail" type="{http://rosreestr.ru/services/v0.1/commons/Commons}SEMail"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAcceptActionNotification", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons", propOrder = {
    "postAddress",
    "eMail"
})
public class TAcceptActionNotification {

    protected TAddress postAddress;
    protected String eMail;

    /**
     * Gets the value of the postAddress property.
     *
     * @return
     *     possible object is
     *     {@link TAddress }
     *
     */
    public TAddress getPostAddress() {
        return postAddress;
    }

    /**
     * Sets the value of the postAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link TAddress }
     *
     */
    public void setPostAddress(TAddress value) {
        this.postAddress = value;
    }

    /**
     * Gets the value of the eMail property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEMail() {
        return eMail;
    }

    /**
     * Sets the value of the eMail property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEMail(String value) {
        this.eMail = value;
    }

}
