//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ � �������� ����������� ����������
 *
 * <p>Java class for TBasicResultDeliveryMethod complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TBasicResultDeliveryMethod">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recieveResultTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="courierAddress" type="{http://rosreestr.ru/services/v0.1/commons/Address}TAddress"/>
 *           &lt;element name="postAddress" type="{http://rosreestr.ru/services/v0.1/commons/Address}TAddress"/>
 *           &lt;element name="eMail" type="{http://rosreestr.ru/services/v0.1/commons/Commons}SEMail"/>
 *         &lt;/choice>
 *         &lt;element name="acceptActionNotification" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TAcceptActionNotification" minOccurs="0"/>
 *         &lt;element name="failSuspendEMail" type="{http://rosreestr.ru/services/v0.1/commons/Commons}SEMail" minOccurs="0"/>
 *         &lt;element name="receiveDischarge" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="receiveReceiptInPrivate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="dataReceiveForm" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}DDataReceiveForm" minOccurs="0"/>
 *         &lt;element name="doNotSendRecieveNotification" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBasicResultDeliveryMethod", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons", propOrder = {
    "recieveResultTypeCode",
    "courierAddress",
    "postAddress",
    "eMail",
    "acceptActionNotification",
    "failSuspendEMail",
    "receiveDischarge",
    "receiveReceiptInPrivate",
    "dataReceiveForm",
    "doNotSendRecieveNotification"
})
//@XmlSeeAlso({
//    TResultDeliveryMethod.class,
//    TEGRNRequestResultDeliveryMethod.class
//})
public class TBasicResultDeliveryMethod {

    @XmlElement(required = true)
    protected String recieveResultTypeCode;
    protected TAddress courierAddress;
    protected TAddress postAddress;
    protected String eMail;
    protected TAcceptActionNotification acceptActionNotification;
    protected String failSuspendEMail;
    protected Boolean receiveDischarge;
    @XmlElement(defaultValue = "true")
    protected Boolean receiveReceiptInPrivate;
    protected DDataReceiveForm dataReceiveForm;
    @XmlElement(defaultValue = "true")
    protected Boolean doNotSendRecieveNotification;

    /**
     * Gets the value of the recieveResultTypeCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRecieveResultTypeCode() {
        return recieveResultTypeCode;
    }

    /**
     * Sets the value of the recieveResultTypeCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRecieveResultTypeCode(String value) {
        this.recieveResultTypeCode = value;
    }

    /**
     * Gets the value of the courierAddress property.
     *
     * @return
     *     possible object is
     *     {@link TAddress }
     *
     */
    public TAddress getCourierAddress() {
        return courierAddress;
    }

    /**
     * Sets the value of the courierAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link TAddress }
     *
     */
    public void setCourierAddress(TAddress value) {
        this.courierAddress = value;
    }

    /**
     * Gets the value of the postAddress property.
     *
     * @return
     *     possible object is
     *     {@link TAddress }
     *
     */
    public TAddress getPostAddress() {
        return postAddress;
    }

    /**
     * Sets the value of the postAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link TAddress }
     *
     */
    public void setPostAddress(TAddress value) {
        this.postAddress = value;
    }

    /**
     * Gets the value of the eMail property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEMail() {
        return eMail;
    }

    /**
     * Sets the value of the eMail property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEMail(String value) {
        this.eMail = value;
    }

    /**
     * Gets the value of the acceptActionNotification property.
     *
     * @return
     *     possible object is
     *     {@link TAcceptActionNotification }
     *
     */
    public TAcceptActionNotification getAcceptActionNotification() {
        return acceptActionNotification;
    }

    /**
     * Sets the value of the acceptActionNotification property.
     *
     * @param value
     *     allowed object is
     *     {@link TAcceptActionNotification }
     *
     */
    public void setAcceptActionNotification(TAcceptActionNotification value) {
        this.acceptActionNotification = value;
    }

    /**
     * Gets the value of the failSuspendEMail property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFailSuspendEMail() {
        return failSuspendEMail;
    }

    /**
     * Sets the value of the failSuspendEMail property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFailSuspendEMail(String value) {
        this.failSuspendEMail = value;
    }

    /**
     * Gets the value of the receiveDischarge property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isReceiveDischarge() {
        return receiveDischarge;
    }

    /**
     * Sets the value of the receiveDischarge property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setReceiveDischarge(Boolean value) {
        this.receiveDischarge = value;
    }

    /**
     * Gets the value of the receiveReceiptInPrivate property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isReceiveReceiptInPrivate() {
        return receiveReceiptInPrivate;
    }

    /**
     * Sets the value of the receiveReceiptInPrivate property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setReceiveReceiptInPrivate(Boolean value) {
        this.receiveReceiptInPrivate = value;
    }

    /**
     * Gets the value of the dataReceiveForm property.
     *
     * @return
     *     possible object is
     *     {@link DDataReceiveForm }
     *
     */
    public DDataReceiveForm getDataReceiveForm() {
        return dataReceiveForm;
    }

    /**
     * Sets the value of the dataReceiveForm property.
     *
     * @param value
     *     allowed object is
     *     {@link DDataReceiveForm }
     *
     */
    public void setDataReceiveForm(DDataReceiveForm value) {
        this.dataReceiveForm = value;
    }

    /**
     * Gets the value of the doNotSendRecieveNotification property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isDoNotSendRecieveNotification() {
        return doNotSendRecieveNotification;
    }

    /**
     * Sets the value of the doNotSendRecieveNotification property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDoNotSendRecieveNotification(Boolean value) {
        this.doNotSendRecieveNotification = value;
    }

}
