//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ � �������� ��������� � ����
 *
 * <p>Java class for TBasicRequestDeliveryMethod complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TBasicRequestDeliveryMethod">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="receivingMethodCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regRightAuthority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialistNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBasicRequestDeliveryMethod", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons", propOrder = {
    "receivingMethodCode",
    "regRightAuthority",
    "code",
    "specialistNote"
})
@XmlSeeAlso({
    TEGRNRequestDeliveryMethod.class,
    TRequestDeliveryMethod.class
})
public class TBasicRequestDeliveryMethod {

    protected String receivingMethodCode;
    protected String regRightAuthority;
    protected String code;
    protected String specialistNote;

    /**
     * Gets the value of the receivingMethodCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReceivingMethodCode() {
        return receivingMethodCode;
    }

    /**
     * Sets the value of the receivingMethodCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReceivingMethodCode(String value) {
        this.receivingMethodCode = value;
    }

    /**
     * Gets the value of the regRightAuthority property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRegRightAuthority() {
        return regRightAuthority;
    }

    /**
     * Sets the value of the regRightAuthority property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRegRightAuthority(String value) {
        this.regRightAuthority = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the specialistNote property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSpecialistNote() {
        return specialistNote;
    }

    /**
     * Sets the value of the specialistNote property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSpecialistNote(String value) {
        this.specialistNote = value;
    }

}
