//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import lombok.Data;
import smev.utils.LocalDateTimeAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for TBasicStatementHeader complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TBasicStatementHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actionCode" type="{http://rosreestr.ru/services/v0.1/commons/directories/actionCode}DActionCode" minOccurs="0"/>
 *         &lt;element name="statementType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="kind" type="{http://rosreestr.ru/services/v0.1/commons/directories/kindInfo}DKindInfo" minOccurs="0"/>
 *         &lt;element name="appliedDocument" type="{http://rosreestr.ru/services/v0.1/commons/Documents}TBasicSomeDocument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="serviceInfo" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBasicServiceInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBasicStatementHeader", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons", propOrder = {
        "actionCode",
        "statementType",
        "creationDate",
        "kind",
        "appliedDocument",
        "serviceInfo"
})
@XmlSeeAlso({
        TStatementFormChangeRegisteredStatementHeader.class,
        TInterdepStatementHeader.class,
        TStatementHeader.class
})
@Data
public class TBasicStatementHeader {

    protected String actionCode;
    protected String statementType;
    //    @XmlSchemaType(name = "dateTime")
    @XmlJavaTypeAdapter(value = LocalDateTimeAdapter.class)
    protected LocalDateTime creationDate;

    protected String kind;
    protected List<TBasicSomeDocument> appliedDocument;
    protected TBasicServiceInfo serviceInfo;

    /**
     * Gets the value of the actionCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getActionCode() {
        return actionCode;
    }

    /**
     * Sets the value of the actionCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setActionCode(String value) {
        this.actionCode = value;
    }

    /**
     * Gets the value of the statementType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatementType() {
        return statementType;
    }

    /**
     * Sets the value of the statementType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatementType(String value) {
        this.statementType = value;
    }

    /**
     * Gets the value of the creationDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public LocalDateTime getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setCreationDate(LocalDateTime value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the kind property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKind(String value) {
        this.kind = value;
    }

    /**
     * Gets the value of the appliedDocument property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appliedDocument property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppliedDocument().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TBasicSomeDocument }
     */
    public List<TBasicSomeDocument> getAppliedDocument() {
        if (appliedDocument == null) {
            appliedDocument = new ArrayList<TBasicSomeDocument>();
        }
        return this.appliedDocument;
    }

    /**
     * Gets the value of the serviceInfo property.
     *
     * @return possible object is
     * {@link TBasicServiceInfo }
     */
    public TBasicServiceInfo getServiceInfo() {
        return serviceInfo;
    }

    /**
     * Sets the value of the serviceInfo property.
     *
     * @param value allowed object is
     *              {@link TBasicServiceInfo }
     */
    public void setServiceInfo(TBasicServiceInfo value) {
        this.serviceInfo = value;
    }

}
