//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * ���������� � �������� ��������� � ���� � ����������� �� ���� � ����������
 *
 * <p>Java class for TBasicDeliveryDetails complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TBasicDeliveryDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestDeliveryMethod" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBasicRequestDeliveryMethod" minOccurs="0"/>
 *         &lt;element name="resultDeliveryMethod" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBasicResultDeliveryMethod" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBasicDeliveryDetails", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons", propOrder = {
    "requestDeliveryMethod",
    "resultDeliveryMethod"
})
@XmlSeeAlso({
    TEGRNRequestDeliveryDetails.class,
    TAppliedDocumentsDeliveryDetails.class,
    TDeliveryDetails.class
})
public class TBasicDeliveryDetails {

    protected TBasicRequestDeliveryMethod requestDeliveryMethod;
    protected TBasicResultDeliveryMethod resultDeliveryMethod;

    /**
     * Gets the value of the requestDeliveryMethod property.
     *
     * @return
     *     possible object is
     *     {@link TBasicRequestDeliveryMethod }
     *
     */
    public TBasicRequestDeliveryMethod getRequestDeliveryMethod() {
        return requestDeliveryMethod;
    }

    /**
     * Sets the value of the requestDeliveryMethod property.
     *
     * @param value
     *     allowed object is
     *     {@link TBasicRequestDeliveryMethod }
     *
     */
    public void setRequestDeliveryMethod(TBasicRequestDeliveryMethod value) {
        this.requestDeliveryMethod = value;
    }

    /**
     * Gets the value of the resultDeliveryMethod property.
     *
     * @return
     *     possible object is
     *     {@link TBasicResultDeliveryMethod }
     *
     */
    public TBasicResultDeliveryMethod getResultDeliveryMethod() {
        return resultDeliveryMethod;
    }

    /**
     * Sets the value of the resultDeliveryMethod property.
     *
     * @param value
     *     allowed object is
     *     {@link TBasicResultDeliveryMethod }
     *
     */
    public void setResultDeliveryMethod(TBasicResultDeliveryMethod value) {
        this.resultDeliveryMethod = value;
    }

}
