//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * ������� ��� ��� ���������������� ���������� � ����������
 *
 * <p>Java class for TBasicStatementAgreements complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TBasicStatementAgreements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="persDataProcessingAgreement" type="{http://rosreestr.ru/services/v0.1/commons/directories/agreements}DPersDataAgreements"/>
 *         &lt;element name="actualDataAgreement" type="{http://rosreestr.ru/services/v0.1/commons/directories/agreements}DActualDataAgreements"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="qualityOfServiceAgreement" type="{http://rosreestr.ru/services/v0.1/commons/directories/agreements}DQualityOfServiceAgreements"/>
 *           &lt;element name="qualityOfServiceTelephoneNumber" type="{http://rosreestr.ru/services/v0.1/commons/Commons}SPhoneNumber" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBasicStatementAgreements", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons", propOrder = {
    "persDataProcessingAgreement",
    "actualDataAgreement",
    "qualityOfServiceAgreement",
    "qualityOfServiceTelephoneNumber"
})
@XmlSeeAlso({
    TStatementAgreements.class,
    TEGRNRequestAgreements.class,
    TInterdepStatementAgreements.class
})
public class TBasicStatementAgreements {

    @XmlElement(required = true)
    protected String persDataProcessingAgreement;
    @XmlElement(required = true)
    protected String actualDataAgreement;
    protected String qualityOfServiceAgreement;
    protected String qualityOfServiceTelephoneNumber;

    /**
     * Gets the value of the persDataProcessingAgreement property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPersDataProcessingAgreement() {
        return persDataProcessingAgreement;
    }

    /**
     * Sets the value of the persDataProcessingAgreement property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPersDataProcessingAgreement(String value) {
        this.persDataProcessingAgreement = value;
    }

    /**
     * Gets the value of the actualDataAgreement property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getActualDataAgreement() {
        return actualDataAgreement;
    }

    /**
     * Sets the value of the actualDataAgreement property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setActualDataAgreement(String value) {
        this.actualDataAgreement = value;
    }

    /**
     * Gets the value of the qualityOfServiceAgreement property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQualityOfServiceAgreement() {
        return qualityOfServiceAgreement;
    }

    /**
     * Sets the value of the qualityOfServiceAgreement property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQualityOfServiceAgreement(String value) {
        this.qualityOfServiceAgreement = value;
    }

    /**
     * Gets the value of the qualityOfServiceTelephoneNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQualityOfServiceTelephoneNumber() {
        return qualityOfServiceTelephoneNumber;
    }

    /**
     * Sets the value of the qualityOfServiceTelephoneNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQualityOfServiceTelephoneNumber(String value) {
        this.qualityOfServiceTelephoneNumber = value;
    }

}
