//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TBasicServiceInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TBasicServiceInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestCause" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="legalActSection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="answerDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="paymentFree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="legalAct" type="{http://rosreestr.ru/services/v0.1/commons/Documents}TStrictDocument" minOccurs="0"/>
 *         &lt;element name="post" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBasicServiceInfo", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons", propOrder = {
    "serviceName",
    "serviceCode",
    "requestCause",
    "legalActSection",
    "answerDate",
    "paymentFree",
    "legalAct",
    "post"
})
//@XmlSeeAlso({
//    TServiceInfo.class,
//    TEGRNRequestServiceInfo.class
//})
public class TBasicServiceInfo {

    protected String serviceName;
    protected String serviceCode;
    protected String requestCause;
    protected String legalActSection;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar answerDate;
    @XmlElement(defaultValue = "заявитель обладает правом на получение сведений, предусмотренных частями 13 - 16 статьи 62 Федерального закона от 13 июля 1997 г. N 218-ФЗ О государственной регистрации недвижимости, и (или) на безвозмездное предоставление сведений в соответствии со статьей 63 данного Федерального закона, иным федеральным законом")
    protected String paymentFree;
    protected TStrictDocument legalAct;
    protected String post;

    /**
     * Gets the value of the serviceName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the serviceCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the requestCause property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRequestCause() {
        return requestCause;
    }

    /**
     * Sets the value of the requestCause property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRequestCause(String value) {
        this.requestCause = value;
    }

    /**
     * Gets the value of the legalActSection property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLegalActSection() {
        return legalActSection;
    }

    /**
     * Sets the value of the legalActSection property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLegalActSection(String value) {
        this.legalActSection = value;
    }

    /**
     * Gets the value of the answerDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getAnswerDate() {
        return answerDate;
    }

    /**
     * Sets the value of the answerDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setAnswerDate(XMLGregorianCalendar value) {
        this.answerDate = value;
    }

    /**
     * Gets the value of the paymentFree property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPaymentFree() {
        return paymentFree;
    }

    /**
     * Sets the value of the paymentFree property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPaymentFree(String value) {
        this.paymentFree = value;
    }

    /**
     * Gets the value of the legalAct property.
     *
     * @return
     *     possible object is
     *     {@link TStrictDocument }
     *
     */
    public TStrictDocument getLegalAct() {
        return legalAct;
    }

    /**
     * Sets the value of the legalAct property.
     *
     * @param value
     *     allowed object is
     *     {@link TStrictDocument }
     *
     */
    public void setLegalAct(TStrictDocument value) {
        this.legalAct = value;
    }

    /**
     * Gets the value of the post property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPost(String value) {
        this.post = value;
    }

}
