//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ �� �������������� �������� � ���� ����� ����������
 *
 * <p>Java class for TEGRNRequestCopyAction complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TEGRNRequestCopyAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="document" type="{http://rosreestr.ru/services/v0.1/commons/Documents}TRequestDocument" maxOccurs="unbounded"/>
 *         &lt;element name="object" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TCopyActionObject"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEGRNRequestCopyAction", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
    "document"
//    "object"
})
public class TEGRNRequestCopyAction {

    @XmlElement(required = true)
    protected List<TRequestDocument> document;
//    @XmlElement(required = true)
//    protected TCopyActionObject object;

    /**
     * Gets the value of the document property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRequestDocument }
     *
     *
     */
    public List<TRequestDocument> getDocument() {
        if (document == null) {
            document = new ArrayList<TRequestDocument>();
        }
        return this.document;
    }


//    public TCopyActionObject getObject() {
//        return object;
//    }
//
//
//    public void setObject(TCopyActionObject value) {
//        this.object = value;
//    }

}
