//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ��������������� ��������� ��������� �� �������������� ��������
 *
 * <p>Java class for TEGRNRequestHeader complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TEGRNRequestHeader">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBaseEGRNRequestHeader">
 *       &lt;sequence>
 *         &lt;element name="genuinenessOfSignature" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TGenuinenessOfSignature" minOccurs="0"/>
 *         &lt;element name="accessKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEGRNRequestHeader", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons", propOrder = {
//    "genuinenessOfSignature",
    "accessKey"
})
public class TEGRNRequestHeader
    extends TBaseEGRNRequestHeader
{

//    protected TGenuinenessOfSignature genuinenessOfSignature;
    protected String accessKey;


//    public TGenuinenessOfSignature getGenuinenessOfSignature() {
//        return genuinenessOfSignature;
//    }


//    public void setGenuinenessOfSignature(TGenuinenessOfSignature value) {
//        this.genuinenessOfSignature = value;
//    }

    /**
     * Gets the value of the accessKey property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAccessKey() {
        return accessKey;
    }

    /**
     * Sets the value of the accessKey property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAccessKey(String value) {
        this.accessKey = value;
    }

}
