//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for TEGRNRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TEGRNRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TEGRNRequestHeader"/>
 *         &lt;element name="declarant" type="{http://rosreestr.ru/services/v0.1/commons/Subjects}TEGRNRequestDeclarant"/>
 *         &lt;element name="requestDetails" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TEGRNRequestDetails"/>
 *         &lt;element name="deliveryDetails" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TEGRNRequestDeliveryDetails"/>
 *         &lt;element name="statementAgreements" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TEGRNRequestAgreements"/>
 *       &lt;/sequence>
 *       &lt;attribute name="_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEGRNRequest", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
    "header",
    "declarant",
    "requestDetails",
    "deliveryDetails",
    "statementAgreements"
})
@XmlRootElement(name = "EGRNRequest", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN")
public class  TEGRNRequest {


    @XmlElement(required = true)
    protected TEGRNRequestHeader header;
    @XmlElement(required = true)
    protected TEGRNRequestDeclarant declarant;
    @XmlElement(required = true)
    protected TEGRNRequestDetails requestDetails;
    @XmlElement(required = true)
    protected TEGRNRequestDeliveryDetails deliveryDetails;
    @XmlElement(required = true)
    protected TEGRNRequestAgreements statementAgreements;
    @XmlAttribute(name = "_id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the header property.
     *
     * @return
     *     possible object is
     *     {@link TEGRNRequestHeader }
     *
     */
    public TEGRNRequestHeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value
     *     allowed object is
     *     {@link TEGRNRequestHeader }
     *
     */
    public void setHeader(TEGRNRequestHeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the declarant property.
     *
     * @return
     *     possible object is
     *     {@link TEGRNRequestDeclarant }
     *
     */
    public TEGRNRequestDeclarant getDeclarant() {
        return declarant;
    }

    /**
     * Sets the value of the declarant property.
     *
     * @param value
     *     allowed object is
     *     {@link TEGRNRequestDeclarant }
     *
     */
    public void setDeclarant(TEGRNRequestDeclarant value) {
        this.declarant = value;
    }

    /**
     * Gets the value of the requestDetails property.
     *
     * @return
     *     possible object is
     *     {@link TEGRNRequestDetails }
     *
     */
    public TEGRNRequestDetails getRequestDetails() {
        return requestDetails;
    }

    /**
     * Sets the value of the requestDetails property.
     *
     * @param value
     *     allowed object is
     *     {@link TEGRNRequestDetails }
     *
     */
    public void setRequestDetails(TEGRNRequestDetails value) {
        this.requestDetails = value;
    }

    /**
     * Gets the value of the deliveryDetails property.
     *
     * @return
     *     possible object is
     *     {@link TEGRNRequestDeliveryDetails }
     *
     */
    public TEGRNRequestDeliveryDetails getDeliveryDetails() {
        return deliveryDetails;
    }

    /**
     * Sets the value of the deliveryDetails property.
     *
     * @param value
     *     allowed object is
     *     {@link TEGRNRequestDeliveryDetails }
     *
     */
    public void setDeliveryDetails(TEGRNRequestDeliveryDetails value) {
        this.deliveryDetails = value;
    }

    /**
     * Gets the value of the statementAgreements property.
     *
     * @return
     *     possible object is
     *     {@link TEGRNRequestAgreements }
     *
     */
    public TEGRNRequestAgreements getStatementAgreements() {
        return statementAgreements;
    }

    /**
     * Sets the value of the statementAgreements property.
     *
     * @param value
     *     allowed object is
     *     {@link TEGRNRequestAgreements }
     *
     */
    public void setStatementAgreements(TEGRNRequestAgreements value) {
        this.statementAgreements = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

}
