//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ ��������� �� �������������� ��������
 *
 * <p>Java class for TEGRNRequestDetails complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TEGRNRequestDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="requestCopyAction" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TEGRNRequestCopyAction"/>
 *           &lt;element name="requestEGRNDataAction" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRequestDataAction"/>
 *           &lt;element name="requestEGRNAccessAction" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRequestEGRNAccessAct"/>
 *           &lt;element name="requestEGRNNotification" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRequestEGRNNotification"/>
 *         &lt;/choice>
 *         &lt;element name="note" type="{http://rosreestr.ru/services/v0.1/commons/Commons}TNote" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEGRNRequestDetails", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
    "requestCopyAction",
    "requestEGRNDataAction",
//    "requestEGRNAccessAction",
    "requestEGRNNotification",
    "note"
})
@Data
public class TEGRNRequestDetails {

    protected TEGRNRequestCopyAction requestCopyAction;
    protected TRequestDataAction requestEGRNDataAction;
//    protected TRequestEGRNAccessAct requestEGRNAccessAction;
    protected TRequestEGRNNotification requestEGRNNotification;
    protected List<TNote> note;

    public List<TNote> getNote() {
        if (note == null) {
            note = new ArrayList<TNote>();
        }
        return this.note;
    }

}
