//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.03 at 11:32:46 PM MSK
//


package smev.ElementServices.Rosreestr;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * ������� �� ���� � ������ ���������� ���� �� ���������/��������� � ���� ��
 *
 * <p>Java class for TExtractSubjectAction complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TExtractSubjectAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="owner" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TEGRNRequestOwnerParams" maxOccurs="unbounded"/>
 *         &lt;element name="period" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TPeriod"/>
 *         &lt;element name="realtyTypes" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRealtyTypes"/>
 *         &lt;element name="territory" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TTerritory"/>
 *         &lt;element name="uptodateData" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TExtractSubjectAction", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
    "owner",
    "period",
    "realtyTypes",
    "territory",
    "uptodateData"
})
@Data
public class TExtractSubjectAction {

    @XmlElement(required = true)
    protected List<TEGRNRequestOwnerParams> owner;
    @XmlElement(required = true)
    protected TPeriod period;
    @XmlElement(required = true)
    protected TRealtyTypes realtyTypes;
    @XmlElement(required = true)
    protected TTerritory territory;
    protected Boolean uptodateData;

    /**
     * Gets the value of the owner property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the owner property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwner().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEGRNRequestOwnerParams }
     *
     *
     */
    public List<TEGRNRequestOwnerParams> getOwner() {
        if (owner == null) {
            owner = new ArrayList<TEGRNRequestOwnerParams>();
        }
        return this.owner;
    }

    /**
     * Gets the value of the period property.
     *
     * @return
     *     possible object is
     *     {@link TPeriod }
     *
     */
    public TPeriod getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     *
     * @param value
     *     allowed object is
     *     {@link TPeriod }
     *
     */
    public void setPeriod(TPeriod value) {
        this.period = value;
    }

    /**
     * Gets the value of the realtyTypes property.
     *
     * @return
     *     possible object is
     *     {@link TRealtyTypes }
     *
     */
    public TRealtyTypes getRealtyTypes() {
        return realtyTypes;
    }

    /**
     * Sets the value of the realtyTypes property.
     *
     * @param value
     *     allowed object is
     *     {@link TRealtyTypes }
     *
     */
    public void setRealtyTypes(TRealtyTypes value) {
        this.realtyTypes = value;
    }

    /**
     * Gets the value of the territory property.
     *
     * @return
     *     possible object is
     *     {@link TTerritory }
     *
     */
    public TTerritory getTerritory() {
        return territory;
    }

    /**
     * Sets the value of the territory property.
     *
     * @param value
     *     allowed object is
     *     {@link TTerritory }
     *
     */
    public void setTerritory(TTerritory value) {
        this.territory = value;
    }

    /**
     * Gets the value of the uptodateData property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isUptodateData() {
        return uptodateData;
    }

    /**
     * Sets the value of the uptodateData property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setUptodateData(Boolean value) {
        this.uptodateData = value;
    }

}
