//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TInterdepStatementHeader complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TInterdepStatementHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBasicStatementHeader">
 *       &lt;sequence>
 *         &lt;element name="actionCode" type="{http://rosreestr.ru/services/v0.1/commons/directories/actionCode}DActionCode"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="kind">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://rosreestr.ru/services/v0.1/commons/directories/kindInfo}DKindInfo">
 *               &lt;pattern value="03"/>
 *               &lt;pattern value="04"/>
 *               &lt;pattern value="05"/>
 *               &lt;pattern value="06"/>
 *               &lt;pattern value="07"/>
 *               &lt;pattern value="08"/>
 *               &lt;pattern value="09"/>
 *               &lt;pattern value="10"/>
 *               &lt;pattern value="11"/>
 *               &lt;pattern value="12"/>
 *               &lt;pattern value="13"/>
 *               &lt;pattern value="14"/>
 *               &lt;pattern value="15"/>
 *               &lt;pattern value="16"/>
 *               &lt;pattern value="17"/>
 *               &lt;pattern value="18"/>
 *               &lt;pattern value="19"/>
 *               &lt;pattern value="20"/>
 *               &lt;pattern value="21"/>
 *               &lt;pattern value="22"/>
 *               &lt;pattern value="23"/>
 *               &lt;pattern value="24"/>
 *               &lt;pattern value="25"/>
 *               &lt;pattern value="26"/>
 *               &lt;pattern value="27"/>
 *               &lt;pattern value="28"/>
 *               &lt;pattern value="29"/>
 *               &lt;pattern value="30"/>
 *               &lt;pattern value="31"/>
 *               &lt;pattern value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="appliedDocument" type="{http://rosreestr.ru/services/v0.1/commons/Documents}TSomeInterdepDocument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="serviceInfo" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TServiceInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TInterdepStatementHeader", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons")
public class TInterdepStatementHeader
    extends TBasicStatementHeader
{


}
