//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import smev.utils.LocalDateAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDate;


/**
 * ������ �������, �� ������� ���������� ������������ ��������
 *
 * <p>Java class for TInterval complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TInterval">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dateEnd" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TInterval", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
    "dateStart",
    "dateEnd"
})
public class TInterval {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate dateStart;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate dateEnd;

    /**
     * Gets the value of the dateStart property.
     *
     * @return
     *     possible object is
     *     {@link LocalDate }
     *
     */
    public LocalDate getDateStart() {
        return dateStart;
    }

    /**
     * Sets the value of the dateStart property.
     *
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *
     */
    public void setDateStart(LocalDate value) {
        this.dateStart = value;
    }

    /**
     * Gets the value of the dateEnd property.
     *
     * @return
     *     possible object is
     *     {@link LocalDate }
     *
     */
    public LocalDate getDateEnd() {
        return dateEnd;
    }

    /**
     * Sets the value of the dateEnd property.
     *
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *
     */
    public void setDateEnd(LocalDate value) {
        this.dateEnd = value;
    }

}
