//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.03 at 11:32:46 PM MSK
//


package smev.ElementServices.Rosreestr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ���� �������� ������������ � ������� � �������������� �������� � ������ ���������� ����
 *
 * <p>Java class for TRealtyTypes complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TRealtyTypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="realtyTypeAll" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="realtyType" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRealtyType" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRealtyTypes", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
    "realtyTypeAll",
    "realtyType"
})
public class TRealtyTypes {

    protected Boolean realtyTypeAll;
    protected List<TRealtyType> realtyType;

    /**
     * Gets the value of the realtyTypeAll property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isRealtyTypeAll() {
        return realtyTypeAll;
    }

    /**
     * Sets the value of the realtyTypeAll property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setRealtyTypeAll(Boolean value) {
        this.realtyTypeAll = value;
    }

    /**
     * Gets the value of the realtyType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realtyType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealtyType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRealtyType }
     *
     *
     */
    public List<TRealtyType> getRealtyType() {
        if (realtyType == null) {
            realtyType = new ArrayList<TRealtyType>();
        }
        return this.realtyType;
    }

}
