//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.03 at 11:32:46 PM MSK
//


package smev.ElementServices.Rosreestr;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ������� ������������
 *
 * <p>Java class for TRealtyType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TRealtyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="parcel" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRealtyParcel"/>
 *         &lt;element name="building" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRealtyBuilding"/>
 *         &lt;element name="room" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRealtyRoom"/>
 *         &lt;element name="other" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRealtyOther"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRealtyType", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
//    "parcel",
//    "building",
//    "room",
//    "other"
})
@Data
public class TRealtyType {

//    protected TRealtyParcel parcel;
//    protected TRealtyBuilding building;
//    protected TRealtyRoom room;
//    protected TRealtyOther other;

}
