////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2021.08.02 at 10:03:24 PM MSK
////
//
//
//package smev.ElementServices.RosreestrEGRN;
//
//import java.util.ArrayList;
//import java.util.List;
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * ������ �� �������������� ������� � ���� ����
// *
// * <p>Java class for TRequestEGRNAccessAct complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="TRequestEGRNAccessAct">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;choice maxOccurs="unbounded">
// *           &lt;element name="requiredDataSubject" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TRequiredData"/>
// *         &lt;/choice>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "TRequestEGRNAccessAct", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
//    "requiredDataSubject"
//})
//public class TRequestEGRNAccessAct {
//
//    protected List<TRequiredData> requiredDataSubject;
//
//    /**
//     * Gets the value of the requiredDataSubject property.
//     *
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the requiredDataSubject property.
//     *
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getRequiredDataSubject().add(newItem);
//     * </pre>
//     *
//     *
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link TRequiredData }
//     *
//     *
//     */
//    public List<TRequiredData> getRequiredDataSubject() {
//        if (requiredDataSubject == null) {
//            requiredDataSubject = new ArrayList<TRequiredData>();
//        }
//        return this.requiredDataSubject;
//    }
//
//}
