//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ �� �������������� ��������
 *
 * <p>Java class for TRequestDataAction complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TRequestDataAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="extractDataAction" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TExtractDataAction"/>
 *           &lt;element name="extractIncapacity" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TExtractIncapacityAction"/>
 *           &lt;element name="extractDocument" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TExtractDocumentAction"/>
 *           &lt;element name="extractSubject" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TExtractSubjectAction"/>
 *           &lt;element name="cadastralPlanTerritory" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TExtractCadastralPlanTerritoryAction"/>
 *           &lt;element name="area" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TExtractAreaAction"/>
 *           &lt;element name="border" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TExtractBorderAction"/>
 *           &lt;element name="aboutPersons" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TAboutPersons"/>
 *           &lt;element name="extractKSObject" type="{http://rosreestr.ru/services/v0.18/TStatementRequestEGRN}TExtractKSObject"/>
 *         &lt;/choice>
 *         &lt;element name="signature" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRequestDataAction", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
//    "extractDataAction",
//    "extractIncapacity",
//    "extractDocument",
    "extractSubject",
//    "cadastralPlanTerritory",
//    "area",
//    "border",
//    "aboutPersons",
//    "extractKSObject",
    "signature"
})
@Data
public class TRequestDataAction {

//    protected TExtractDataAction extractDataAction;
//    protected TExtractIncapacityAction extractIncapacity;
//    protected TExtractDocumentAction extractDocument;
    protected TExtractSubjectAction extractSubject;
//    protected TExtractCadastralPlanTerritoryAction cadastralPlanTerritory;
//    protected TExtractAreaAction area;
//    protected TExtractBorderAction border;
//    protected TAboutPersons aboutPersons;
//    protected TExtractKSObject extractKSObject;
    @XmlElement(defaultValue = "true")
    protected Boolean signature;


}
