//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ �� ��������� ����������� �� ��������� ������������ � ���� ��������
 *
 * <p>Java class for TRequestEGRNNotification complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TRequestEGRNNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objectCadastralNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRequestEGRNNotification", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
    "objectCadastralNumber"
})
public class TRequestEGRNNotification {

    @XmlElement(required = true)
    protected String objectCadastralNumber;

    /**
     * Gets the value of the objectCadastralNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getObjectCadastralNumber() {
        return objectCadastralNumber;
    }

    /**
     * Sets the value of the objectCadastralNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setObjectCadastralNumber(String value) {
        this.objectCadastralNumber = value;
    }

}
