//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ���������������� ���������� � ��������� �� ����������� ����
 *
 * <p>Java class for TStatementAgreements complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TStatementAgreements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBasicStatementAgreements">
 *       &lt;sequence>
 *         &lt;element name="persDataProcessingAgreement" type="{http://rosreestr.ru/services/v0.1/commons/directories/agreements}DPersDataAgreements"/>
 *         &lt;element name="actualDataAgreement" type="{http://rosreestr.ru/services/v0.1/commons/directories/agreements}DActualDataAgreements"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="qualityOfServiceAgreement" type="{http://rosreestr.ru/services/v0.1/commons/directories/agreements}DQualityOfServiceAgreements"/>
 *           &lt;element name="qualityOfServiceTelephoneNumber" type="{http://rosreestr.ru/services/v0.1/commons/Commons}SPhoneNumber"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStatementAgreements", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons")
public class TStatementAgreements
    extends TBasicStatementAgreements
{


}
