//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * ��������������� ��������� ���������
 *
 * <p>Java class for TStatementHeader complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TStatementHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBasicStatementHeader">
 *       &lt;sequence>
 *         &lt;element name="actionCode" type="{http://rosreestr.ru/services/v0.1/commons/directories/actionCode}DActionCode" minOccurs="0"/>
 *         &lt;element name="statementType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="appliedDocument" type="{http://rosreestr.ru/services/v0.1/commons/Documents}TBasicSomeDocument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="serviceInfo" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBasicServiceInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStatementHeader", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons")
@XmlSeeAlso({
    TStatementHeaderFormTechErr.class,
    TStatementHeaderAppliedDocuments.class,
    TBaseEGRNRequestHeader.class,
    TStatementHeaderOwnerless.class,
    TStatementHeaderForm2 .class,
    TStatementHeaderForm3 .class,
    TStatementHeaderForm1 .class,
    TStatementHeaderMortgage.class
})
public class TStatementHeader
    extends TBasicStatementHeader
{


}
