//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.02 at 10:03:24 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ��������������� ��������� ���������
 *
 * <p>Java class for TStatementFormChangeRegisteredStatementHeader complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TStatementFormChangeRegisteredStatementHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBasicStatementHeader">
 *       &lt;sequence>
 *         &lt;element name="actionCode" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}DChangeRegisteredStatementActionCode"/>
 *         &lt;element name="statementType" type="{http://rosreestr.ru/services/v0.1/commons/directories/statementType}DStatementType"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="kind" type="{http://rosreestr.ru/services/v0.1/commons/directories/kindInfo}DKindInfo" minOccurs="0"/>
 *         &lt;element name="appliedDocument" type="{http://rosreestr.ru/services/v0.1/commons/Documents}TBasicSomeDocument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="serviceInfo" type="{http://rosreestr.ru/services/v0.1/TStatementCommons}TBasicServiceInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStatementFormChangeRegisteredStatementHeader", namespace = "http://rosreestr.ru/services/v0.1/TStatementCommons")
public class TStatementFormChangeRegisteredStatementHeader
    extends TBasicStatementHeader
{


}
