//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.04 at 01:57:44 PM MSK
//


package smev.ElementServices.Rosreestr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ��� �����, ������������ � ���������
 *
 * <p>Java class for TStructuredAttachmentFormat complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TStructuredAttachmentFormat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsUnstructuredFormat" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="IsZippedPacket" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStructuredAttachmentFormat", propOrder = {
    "isUnstructuredFormat",
    "isZippedPacket",
    "fileName"
})
public class TStructuredAttachmentFormat {

    @XmlElement(name = "IsUnstructuredFormat", namespace = "urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2")
    protected boolean isUnstructuredFormat;
    @XmlElement(name = "IsZippedPacket", namespace = "urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2")
    protected boolean isZippedPacket;
    @XmlElement(required = true, namespace = "urn://x-artefacts-rosreestr-gov-ru/virtual-services/egrn-statement/1.1.2")
    protected String fileName;

    /**
     * Gets the value of the isUnstructuredFormat property.
     *
     */
    public boolean isIsUnstructuredFormat() {
        return isUnstructuredFormat;
    }

    /**
     * Sets the value of the isUnstructuredFormat property.
     *
     */
    public void setIsUnstructuredFormat(boolean value) {
        this.isUnstructuredFormat = value;
    }

    /**
     * Gets the value of the isZippedPacket property.
     *
     */
    public boolean isIsZippedPacket() {
        return isZippedPacket;
    }

    /**
     * Sets the value of the isZippedPacket property.
     *
     */
    public void setIsZippedPacket(boolean value) {
        this.isZippedPacket = value;
    }

    /**
     * Gets the value of the fileName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

}
