//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.03 at 11:32:46 PM MSK
//


package smev.ElementServices.Rosreestr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ���������� ��
 *
 * <p>Java class for TTerritory complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TTerritory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="territoryRussia" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="regions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="region" type="{http://rosreestr.ru/services/v0.1/commons/directories/regionrf}dRegionsRF" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTerritory", namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", propOrder = {
    "territoryRussia",
    "regions"
})
public class TTerritory {

    protected Boolean territoryRussia;
    protected Regions regions;

    /**
     * Gets the value of the territoryRussia property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isTerritoryRussia() {
        return territoryRussia;
    }

    /**
     * Sets the value of the territoryRussia property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setTerritoryRussia(Boolean value) {
        this.territoryRussia = value;
    }

    /**
     * Gets the value of the regions property.
     *
     * @return
     *     possible object is
     *     {@link Regions }
     *
     */
    public Regions getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     *
     * @param value
     *     allowed object is
     *     {@link Regions }
     *
     */
    public void setRegions(Regions value) {
        this.regions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="region" type="{http://rosreestr.ru/services/v0.1/commons/directories/regionrf}dRegionsRF" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "region"
    })
    public static class Regions {

        @XmlElement(namespace = "http://rosreestr.ru/services/v0.18/TStatementRequestEGRN", required = true)
        protected List<String> region;

        /**
         * Gets the value of the region property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the region property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRegion().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         *
         *
         */
        public List<String> getRegion() {
            if (region == null) {
                region = new ArrayList<String>();
            }
            return this.region;
        }

    }

}
