//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.23 at 10:36:31 AM AMT
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn://x-artefacts-fns-dohflna/root/260-18/4.0.1",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @XmlNs(prefix="ns1", namespaceURI="urn://x-artefacts-fns-dohflna/root/260-18/4.0.1"),
                @XmlNs(prefix="ns2", namespaceURI="urn://x-artefacts-fns-ndfl3doh/root/210-18/4.0.2"),
                @XmlNs(prefix="ns3", namespaceURI="urn://x-artefacts-fns-dohflnasp/types/4.0.0"),
                @XmlNs(prefix="ns4", namespaceURI="urn://x-artefacts-fns-dohflnasp/types/4.0.0"),
                @XmlNs(prefix="ns5", namespaceURI="urn://x-artefacts-fns-ndfl2/types/4.1.1")
        }
)
package smev.ElementServices.Dohflna;

import javax.xml.bind.annotation.XmlNs;
