
package smev.ElementServices.Inn;

import javax.xml.bind.annotation.XmlRegistry;


@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.voskhod.smev.server.autogenerated.types.v1_2
     *
     */
    public ObjectFactory() {
    }

    public FNSINNSingularRequest createFNSINNSingularRequest() {
        return new FNSINNSingularRequest();
    }

    public FNSINNSingularResponse createFNSINNSingularResponse() {
        return new FNSINNSingularResponse();
    }


}
