//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.06.23 at 09:14:31 PM AMT
//


package smev.ElementServices.Inn;

import lombok.Data;
import smev.utils.LocalDateAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDate;

/**
 *
 * Сведения о физическом лице
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SvedFlType", namespace = "urn://x-artefacts-fns-inn/commons/4.0.0", propOrder = {
    "fio",
    "udLichFl"
})
@Data
public class SvedFlType {

    @XmlElement(name = "ФИО", namespace = "urn://x-artefacts-fns-inn/commons/4.0.0", required = true)
    protected FioType fio;

    @XmlElement(name = "УдЛичнФЛ", namespace = "urn://x-artefacts-fns-inn/commons/4.0.0", required = true)
    protected UdLichFlType udLichFl;

    @XmlAttribute(name = "ДатаРожд", required = true)
    //@XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(value = LocalDateAdapter.class)
    protected LocalDate birthday;

    @XmlAttribute(name = "МестоРожд")
    protected String placeBirthday;
}
