//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.28 at 01:08:54 PM AMT
//


package smev.Egisso.Elements.ElementsProtocol;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *
 *         ��� ������: ������
 *
 *
 * <p>Java class for tError complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tError">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-10" minOccurs="0"/>
 *         &lt;element name="message" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-200"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tError", namespace = "urn://egisso-ru/types/basic/1.0.2", propOrder = {
    "code",
    "message",
    "time"
})
@Data
public class TError {

    protected String code;
    @XmlElement(required = true)
    protected String message;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar time;

}
