//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.23 at 10:36:31 AM AMT
//


package smev.ElementServices.infoEgissoBySnils;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the infoEgissoBySnils package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

//    private final static QName _SovietPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "SovietPassport");
//    private final static QName _Form9Certificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "Form9Certificate");
//    private final static QName _PrimaryIdentityDocument_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "PrimaryIdentityDocument");
//    private final static QName _BirthCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "BirthCertificate");
//    private final static QName _TemporaryIdentityCardRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "TemporaryIdentityCardRF");
//    private final static QName _PassportRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "PassportRF");
//    private final static QName _MilitaryPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "MilitaryPassport");
//    private final static QName _ResidencePermitRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "ResidencePermitRF");
//    private final static QName _InternationalPassportRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "InternationalPassportRF");
//    private final static QName _DrivingLicenseRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "DrivingLicenseRF");
//    private final static QName _ReleaseCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "ReleaseCertificate");
//    private final static QName _AttachmentRef_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "AttachmentRef");
//    private final static QName _StatementData_QNAME = new QName("urn://egisso-ru/types/prsn-statement/1.0.3", "statementData");
//    private final static QName _ForeignPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "ForeignPassport");
//    private final static QName _RequestData_QNAME = new QName("urn://egisso-ru/types/prsn-request/1.0.3", "requestData");
//    private final static QName _PassportLossCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "PassportLossCertificate");
//    private final static QName _SailorPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "SailorPassport");
//    private final static QName _IdentityDocument_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "IdentityDocument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: infoEgissoBySnils
     *
     */
    public ObjectFactory() {
    }

//    /**
//     * Create an instance of {@link TObligationData }
//     *
//     */
//    public TObligationData createTObligationData() {
//        return new TObligationData();
//    }
//
//    /**
//     * Create an instance of {@link TObligationData.Obligation }
//     *
//     */
//    public TObligationData.Obligation createTObligationDataObligation() {
//        return new TObligationData.Obligation();
//    }
//
//    /**
//     * Create an instance of {@link TAssigneeData }
//     *
//     */
//    public TAssigneeData createTAssigneeData() {
//        return new TAssigneeData();
//    }
//
//    /**
//     * Create an instance of {@link TIncomes }
//     *
//     */
//    public TIncomes createTIncomes() {
//        return new TIncomes();
//    }
//
//    /**
//     * Create an instance of {@link TAssignmentData }
//     *
//     */
//    public TAssignmentData createTAssignmentData() {
//        return new TAssignmentData();
//    }
//
//    /**
//     * Create an instance of {@link TAssignmentData.Assignment }
//     *
//     */
//    public TAssignmentData.Assignment createTAssignmentDataAssignment() {
//        return new TAssignmentData.Assignment();
//    }
//
//    /**
//     * Create an instance of {@link TAssignmentData.Assignment.NpaList }
//     *
//     */
//    public TAssignmentData.Assignment.NpaList createTAssignmentDataAssignmentNpaList() {
//        return new TAssignmentData.Assignment.NpaList();
//    }
//
//    /**
//     * Create an instance of {@link TAssignmentData.Assignment.RightsDocuments }
//     *
//     */
//    public TAssignmentData.Assignment.RightsDocuments createTAssignmentDataAssignmentRightsDocuments() {
//        return new TAssignmentData.Assignment.RightsDocuments();
//    }
//
//    /**
//     * Create an instance of {@link TAssignmentData.Assignment.ReasonPersons }
//     *
//     */
//    public TAssignmentData.Assignment.ReasonPersons createTAssignmentDataAssignmentReasonPersons() {
//        return new TAssignmentData.Assignment.ReasonPersons();
//    }
//
//    /**
//     * Create an instance of {@link TRequestedData }
//     *
//     */
//    public TRequestedData createTRequestedData() {
//        return new TRequestedData();
//    }
//
//    /**
//     * Create an instance of {@link Response }
//     *
//     */
    public Response createResponse() {
        return new Response();
    }
//
//    /**
//     * Create an instance of {@link TStatementData }
//     *
//     */
//    public TStatementData createTStatementData() {
//        return new TStatementData();
//    }
//
//    /**
//     * Create an instance of {@link TError }
//     *
//     */
//    public TError createTError() {
//        return new TError();
//    }
//
//    /**
//     * Create an instance of {@link Request }
//     *
//     */
//    public Request createRequest() {
//        return new Request();
//    }
//
//    /**
//     * Create an instance of {@link NotRestrictedDocumentType }
//     *
//     */
//    public NotRestrictedDocumentType createNotRestrictedDocumentType() {
//        return new NotRestrictedDocumentType();
//    }
//
//    /**
//     * Create an instance of {@link SovietPassportType }
//     *
//     */
//    public SovietPassportType createSovietPassportType() {
//        return new SovietPassportType();
//    }
//
//    /**
//     * Create an instance of {@link PrimaryIdentityDocumentType }
//     *
//     */
//    public PrimaryIdentityDocumentType createPrimaryIdentityDocumentType() {
//        return new PrimaryIdentityDocumentType();
//    }
//
//    /**
//     * Create an instance of {@link MilitaryPassportDocumentType }
//     *
//     */
//    public MilitaryPassportDocumentType createMilitaryPassportDocumentType() {
//        return new MilitaryPassportDocumentType();
//    }
//
//    /**
//     * Create an instance of {@link PassportRFType }
//     *
//     */
//    public PassportRFType createPassportRFType() {
//        return new PassportRFType();
//    }
//
//    /**
//     * Create an instance of {@link DrivingLicenseRFType }
//     *
//     */
//    public DrivingLicenseRFType createDrivingLicenseRFType() {
//        return new DrivingLicenseRFType();
//    }
//
//    /**
//     * Create an instance of {@link InternationalPassportRFType }
//     *
//     */
//    public InternationalPassportRFType createInternationalPassportRFType() {
//        return new InternationalPassportRFType();
//    }
//
//    /**
//     * Create an instance of {@link AttachmentRefType }
//     *
//     */
//    public AttachmentRefType createAttachmentRefType() {
//        return new AttachmentRefType();
//    }
//
//    /**
//     * Create an instance of {@link AnyIdentityDocumentType }
//     *
//     */
//    public AnyIdentityDocumentType createAnyIdentityDocumentType() {
//        return new AnyIdentityDocumentType();
//    }
//
//    /**
//     * Create an instance of {@link TClsVersion }
//     *
//     */
//    public TClsVersion createTClsVersion() {
//        return new TClsVersion();
//    }
//
//    /**
//     * Create an instance of {@link TAddress }
//     *
//     */
//    public TAddress createTAddress() {
//        return new TAddress();
//    }
//
//    /**
//     * Create an instance of {@link TObligationData.Obligation.Payments }
//     *
//     */
//    public TObligationData.Obligation.Payments createTObligationDataObligationPayments() {
//        return new TObligationData.Obligation.Payments();
//    }
//
//    /**
//     * Create an instance of {@link TAssigneeData.Assignee }
//     *
//     */
//    public TAssigneeData.Assignee createTAssigneeDataAssignee() {
//        return new TAssigneeData.Assignee();
//    }
//
//    /**
//     * Create an instance of {@link TIncomes.MonthIncome }
//     *
//     */
//    public TIncomes.MonthIncome createTIncomesMonthIncome() {
//        return new TIncomes.MonthIncome();
//    }
//
//    /**
//     * Create an instance of {@link TAssignmentData.Assignment.NpaList.Npa }
//     *
//     */
//    public TAssignmentData.Assignment.NpaList.Npa createTAssignmentDataAssignmentNpaListNpa() {
//        return new TAssignmentData.Assignment.NpaList.Npa();
//    }
//
//    /**
//     * Create an instance of {@link TAssignmentData.Assignment.RightsDocuments.Document }
//     *
//     */
//    public TAssignmentData.Assignment.RightsDocuments.Document createTAssignmentDataAssignmentRightsDocumentsDocument() {
//        return new TAssignmentData.Assignment.RightsDocuments.Document();
//    }
//
//    /**
//     * Create an instance of {@link TAssignmentData.Assignment.ReasonPersons.ReasonPerson }
//     *
//     */
//    public TAssignmentData.Assignment.ReasonPersons.ReasonPerson createTAssignmentDataAssignmentReasonPersonsReasonPerson() {
//        return new TAssignmentData.Assignment.ReasonPersons.ReasonPerson();
//    }
//
//    /**
//     * Create an instance of {@link TRequestedData.AssignmentsFilter }
//     *
//     */
//    public TRequestedData.AssignmentsFilter createTRequestedDataAssignmentsFilter() {
//        return new TRequestedData.AssignmentsFilter();
//    }
//
//    /**
//     * Create an instance of {@link TRequestedData.ObligationsFilter }
//     *
//     */
//    public TRequestedData.ObligationsFilter createTRequestedDataObligationsFilter() {
//        return new TRequestedData.ObligationsFilter();
//    }
//
//    /**
//     * Create an instance of {@link TRequestedData.ReportPeriod }
//     *
//     */
//    public TRequestedData.ReportPeriod createTRequestedDataReportPeriod() {
//        return new TRequestedData.ReportPeriod();
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "SovietPassport")
//    public JAXBElement<SovietPassportType> createSovietPassport(SovietPassportType value) {
//        return new JAXBElement<SovietPassportType>(_SovietPassport_QNAME, SovietPassportType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "Form9Certificate")
//    public JAXBElement<NotRestrictedDocumentType> createForm9Certificate(NotRestrictedDocumentType value) {
//        return new JAXBElement<NotRestrictedDocumentType>(_Form9Certificate_QNAME, NotRestrictedDocumentType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryIdentityDocumentType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "PrimaryIdentityDocument")
//    public JAXBElement<PrimaryIdentityDocumentType> createPrimaryIdentityDocument(PrimaryIdentityDocumentType value) {
//        return new JAXBElement<PrimaryIdentityDocumentType>(_PrimaryIdentityDocument_QNAME, PrimaryIdentityDocumentType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "BirthCertificate")
//    public JAXBElement<SovietPassportType> createBirthCertificate(SovietPassportType value) {
//        return new JAXBElement<SovietPassportType>(_BirthCertificate_QNAME, SovietPassportType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "TemporaryIdentityCardRF")
//    public JAXBElement<NotRestrictedDocumentType> createTemporaryIdentityCardRF(NotRestrictedDocumentType value) {
//        return new JAXBElement<NotRestrictedDocumentType>(_TemporaryIdentityCardRF_QNAME, NotRestrictedDocumentType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link PassportRFType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "PassportRF")
//    public JAXBElement<PassportRFType> createPassportRF(PassportRFType value) {
//        return new JAXBElement<PassportRFType>(_PassportRF_QNAME, PassportRFType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "MilitaryPassport")
//    public JAXBElement<MilitaryPassportDocumentType> createMilitaryPassport(MilitaryPassportDocumentType value) {
//        return new JAXBElement<MilitaryPassportDocumentType>(_MilitaryPassport_QNAME, MilitaryPassportDocumentType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "ResidencePermitRF")
//    public JAXBElement<InternationalPassportRFType> createResidencePermitRF(InternationalPassportRFType value) {
//        return new JAXBElement<InternationalPassportRFType>(_ResidencePermitRF_QNAME, InternationalPassportRFType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "InternationalPassportRF")
//    public JAXBElement<InternationalPassportRFType> createInternationalPassportRF(InternationalPassportRFType value) {
//        return new JAXBElement<InternationalPassportRFType>(_InternationalPassportRF_QNAME, InternationalPassportRFType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link DrivingLicenseRFType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "DrivingLicenseRF")
//    public JAXBElement<DrivingLicenseRFType> createDrivingLicenseRF(DrivingLicenseRFType value) {
//        return new JAXBElement<DrivingLicenseRFType>(_DrivingLicenseRF_QNAME, DrivingLicenseRFType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "ReleaseCertificate")
//    public JAXBElement<NotRestrictedDocumentType> createReleaseCertificate(NotRestrictedDocumentType value) {
//        return new JAXBElement<NotRestrictedDocumentType>(_ReleaseCertificate_QNAME, NotRestrictedDocumentType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentRefType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "AttachmentRef")
//    public JAXBElement<AttachmentRefType> createAttachmentRef(AttachmentRefType value) {
//        return new JAXBElement<AttachmentRefType>(_AttachmentRef_QNAME, AttachmentRefType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link TStatementData }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", userName = "statementData")
//    public JAXBElement<TStatementData> createStatementData(TStatementData value) {
//        return new JAXBElement<TStatementData>(_StatementData_QNAME, TStatementData.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "ForeignPassport")
//    public JAXBElement<NotRestrictedDocumentType> createForeignPassport(NotRestrictedDocumentType value) {
//        return new JAXBElement<NotRestrictedDocumentType>(_ForeignPassport_QNAME, NotRestrictedDocumentType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link TRequestedData }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://egisso-ru/types/prsn-request/1.0.3", userName = "requestData")
//    public JAXBElement<TRequestedData> createRequestData(TRequestedData value) {
//        return new JAXBElement<TRequestedData>(_RequestData_QNAME, TRequestedData.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "PassportLossCertificate")
//    public JAXBElement<NotRestrictedDocumentType> createPassportLossCertificate(NotRestrictedDocumentType value) {
//        return new JAXBElement<NotRestrictedDocumentType>(_PassportLossCertificate_QNAME, NotRestrictedDocumentType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "SailorPassport")
//    public JAXBElement<MilitaryPassportDocumentType> createSailorPassport(MilitaryPassportDocumentType value) {
//        return new JAXBElement<MilitaryPassportDocumentType>(_SailorPassport_QNAME, MilitaryPassportDocumentType.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link AnyIdentityDocumentType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", userName = "IdentityDocument")
//    public JAXBElement<AnyIdentityDocumentType> createIdentityDocument(AnyIdentityDocumentType value) {
//        return new JAXBElement<AnyIdentityDocumentType>(_IdentityDocument_QNAME, AnyIdentityDocumentType.class, null, value);
//    }

}
