//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.23 at 10:36:31 AM AMT
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
//package ru.uszn.smev.ElementServices.infoEgissoBySnils;
package smev.ElementServices.infoEgissoBySnils;
