//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.23 at 10:36:31 AM AMT
//


package smev.ElementServices.infoEgissoBySnils;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn://egisso-ru/types/prsn-statement/1.0.3}statementData"/>
 *         &lt;element userName="error" type="{urn://egisso-ru/types/basic/1.0.6}tError"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statementData",
    "error"
})
@XmlRootElement(name = "response"
        , namespace = "urn://egisso-ru/msg/10.13.I/1.0.3"
)
public class Response {

    @XmlElement//(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3")
    protected TStatementData statementData;
    @XmlElement//(namespace = "urn://egisso-ru/msg/10.13.I/1.0.3")
    protected TError error;

    /**
     *
     *              Выписка по СНИЛС
     *
     *
     * @return
     *     possible object is
     *     {@link TStatementData }
     *
     */
    public TStatementData getStatementData() {
        return statementData;
    }

    /**
     * Sets the value of the statementData property.
     *
     * @param value
     *     allowed object is
     *     {@link TStatementData }
     *
     */
    public void setStatementData(TStatementData value) {
        this.statementData = value;
    }

    /**
     * Gets the value of the error property.
     *
     * @return
     *     possible object is
     *     {@link TError }
     *
     */
    public TError getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     *
     * @param value
     *     allowed object is
     *     {@link TError }
     *
     */
    public void setError(TError value) {
        this.error = value;
    }

}
