//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.23 at 10:36:31 AM AMT
//


package smev.ElementServices.infoEgissoBySnils;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 *
 *         Тип данных: Сведения о выплатах, полученных в качестве правопреемника
 *
 *
 * <p>Java class for tAssigneeData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType userName="tAssigneeData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element userName="assignee" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element userName="snils" type="{urn://egisso-ru/types/basic/1.0.6}tSnils-9"/>
 *                   &lt;element userName="decisionNumber" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-20"/>
 *                   &lt;element userName="decisionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element userName="assignAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAssigneeData", namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", propOrder = {
    "assignee"
})
public class TAssigneeData {

    protected List<Assignee> assignee;

    /**
     * Gets the value of the assignee property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignee property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignee().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAssigneeData.Assignee }
     *
     *
     */
    public List<Assignee> getAssignee() {
        if (assignee == null) {
            assignee = new ArrayList<Assignee>();
        }
        return this.assignee;
    }


    /**
     *
     *               �������� � �������, ���������� � �������� ��������������
     *
     *
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element userName="snils" type="{urn://egisso-ru/types/basic/1.0.6}tSnils-9"/>
     *         &lt;element userName="decisionNumber" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-20"/>
     *         &lt;element userName="decisionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element userName="assignAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "snils",
        "decisionNumber",
        "decisionDate",
        "assignAmount"
    })
    public static class Assignee {

        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        protected String snils;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        protected String decisionNumber;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar decisionDate;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        protected BigDecimal assignAmount;

        /**
         * Gets the value of the snils property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSnils() {
            return snils;
        }

        /**
         * Sets the value of the snils property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSnils(String value) {
            this.snils = value;
        }

        /**
         * Gets the value of the decisionNumber property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDecisionNumber() {
            return decisionNumber;
        }

        /**
         * Sets the value of the decisionNumber property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDecisionNumber(String value) {
            this.decisionNumber = value;
        }

        /**
         * Gets the value of the decisionDate property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getDecisionDate() {
            return decisionDate;
        }

        /**
         * Sets the value of the decisionDate property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setDecisionDate(XMLGregorianCalendar value) {
            this.decisionDate = value;
        }

        /**
         * Gets the value of the assignAmount property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getAssignAmount() {
            return assignAmount;
        }

        /**
         * Sets the value of the assignAmount property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setAssignAmount(BigDecimal value) {
            this.assignAmount = value;
        }

    }

}
