//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.23 at 10:36:31 AM AMT
//


package smev.ElementServices.infoEgissoBySnils;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 *
 *           Тип данных: Сведения о бюджетных обязательствах для указанного СНИЛС
 *
 *
 * <p>Java class for tObligationData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType userName="tObligationData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element userName="obligation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element userName="kmszCode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="\d{4}\.\d{8}\.\d{2}\.\d{4}\.\d{2}\.\d{6}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element userName="onmszTitle" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-500"/>
 *                   &lt;element userName="lmszTitle">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="2000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element userName="categoryTitle">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="2000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element userName="decisionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element userName="dateStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element userName="dateFinish" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element userName="periodicity" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}digits-2"/>
 *                   &lt;element userName="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element userName="payments" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element userName="year" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element userName="month" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element userName="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tObligationData", namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", propOrder = {
    "obligation"
})
public class TObligationData {

    protected List<Obligation> obligation;

    /**
     * Gets the value of the obligation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obligation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObligation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TObligationData.Obligation }
     *
     *
     */
    public List<Obligation> getObligation() {
        if (obligation == null) {
            obligation = new ArrayList<Obligation>();
        }
        return this.obligation;
    }


    /**
     *
     *               �������� � ��������� �������������� ��� ���������� �����
     *
     *
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element userName="kmszCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="\d{4}\.\d{8}\.\d{2}\.\d{4}\.\d{2}\.\d{6}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element userName="onmszTitle" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-500"/>
     *         &lt;element userName="lmszTitle">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="2000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element userName="categoryTitle">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="2000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element userName="decisionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element userName="dateStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element userName="dateFinish" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element userName="periodicity" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}digits-2"/>
     *         &lt;element userName="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element userName="payments" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element userName="year" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element userName="month" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element userName="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kmszCode",
        "onmszTitle",
        "lmszTitle",
        "categoryTitle",
        "decisionDate",
        "dateStart",
        "dateFinish",
        "periodicity",
        "amount",
        "payments"
    })
    public static class Obligation {

        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        protected String kmszCode;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        protected String onmszTitle;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        protected String lmszTitle;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        protected String categoryTitle;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar decisionDate;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateStart;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateFinish;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        protected String periodicity;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
        protected BigDecimal amount;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3")
        protected List<Payments> payments;

        /**
         * Gets the value of the kmszCode property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getKmszCode() {
            return kmszCode;
        }

        /**
         * Sets the value of the kmszCode property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setKmszCode(String value) {
            this.kmszCode = value;
        }

        /**
         * Gets the value of the onmszTitle property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOnmszTitle() {
            return onmszTitle;
        }

        /**
         * Sets the value of the onmszTitle property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOnmszTitle(String value) {
            this.onmszTitle = value;
        }

        /**
         * Gets the value of the lmszTitle property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLmszTitle() {
            return lmszTitle;
        }

        /**
         * Sets the value of the lmszTitle property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLmszTitle(String value) {
            this.lmszTitle = value;
        }

        /**
         * Gets the value of the categoryTitle property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCategoryTitle() {
            return categoryTitle;
        }

        /**
         * Sets the value of the categoryTitle property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCategoryTitle(String value) {
            this.categoryTitle = value;
        }

        /**
         * Gets the value of the decisionDate property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getDecisionDate() {
            return decisionDate;
        }

        /**
         * Sets the value of the decisionDate property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setDecisionDate(XMLGregorianCalendar value) {
            this.decisionDate = value;
        }

        /**
         * Gets the value of the dateStart property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getDateStart() {
            return dateStart;
        }

        /**
         * Sets the value of the dateStart property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setDateStart(XMLGregorianCalendar value) {
            this.dateStart = value;
        }

        /**
         * Gets the value of the dateFinish property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getDateFinish() {
            return dateFinish;
        }

        /**
         * Sets the value of the dateFinish property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setDateFinish(XMLGregorianCalendar value) {
            this.dateFinish = value;
        }

        /**
         * Gets the value of the periodicity property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPeriodicity() {
            return periodicity;
        }

        /**
         * Sets the value of the periodicity property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPeriodicity(String value) {
            this.periodicity = value;
        }

        /**
         * Gets the value of the amount property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setAmount(BigDecimal value) {
            this.amount = value;
        }

        /**
         * Gets the value of the payments property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the payments property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPayments().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TObligationData.Obligation.Payments }
         *
         *
         */
        public List<Payments> getPayments() {
            if (payments == null) {
                payments = new ArrayList<Payments>();
            }
            return this.payments;
        }


        /**
         *
         *                     �������������
         *
         *
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element userName="year" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element userName="month" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element userName="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "year",
            "month",
            "amount"
        })
        public static class Payments {

            @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger year;
            @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger month;
            @XmlElement(namespace = "urn://egisso-ru/types/prsn-statement/1.0.3", required = true)
            protected BigDecimal amount;

            /**
             * Gets the value of the year property.
             *
             * @return
             *     possible object is
             *     {@link BigInteger }
             *
             */
            public BigInteger getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             *
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *
             */
            public void setYear(BigInteger value) {
                this.year = value;
            }

            /**
             * Gets the value of the month property.
             *
             * @return
             *     possible object is
             *     {@link BigInteger }
             *
             */
            public BigInteger getMonth() {
                return month;
            }

            /**
             * Sets the value of the month property.
             *
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *
             */
            public void setMonth(BigInteger value) {
                this.month = value;
            }

            /**
             * Gets the value of the amount property.
             *
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *
             */
            public BigDecimal getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             *
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *
             */
            public void setAmount(BigDecimal value) {
                this.amount = value;
            }

        }

    }

}
