//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.23 at 10:36:31 AM AMT
//


package smev.ElementServices.infoEgissoBySnils;

import lombok.Builder;
import lombok.Data;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 *
 *              Тип данных: сведения о запрашиваемом получателе МСЗ
 *
 *
 * <p>Java class for tRequestedData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType userName="tRequestedData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element userName="snils" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}SNILSType"/>
 *         &lt;element userName="onmszCode" type="{urn://egisso-ru/types/basic/1.0.6}tParticipantCode" minOccurs="0"/>
 *         &lt;element userName="assignmentsInclude" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element userName="assignmentsFilter" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element userName="form" type="{urn://egisso-ru/types/basic/1.0.6}tFormOfGranting" minOccurs="0"/>
 *                   &lt;element userName="mszCodes" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}digits-4" maxOccurs="250" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element userName="obligationsInclude" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element userName="obligationsFilter" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element userName="mszCodes" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}digits-4" maxOccurs="250" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element userName="incomesInclude" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element userName="assigneeInclude" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element userName="reportPeriod">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element userName="beginDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element userName="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element userName="serviceTitle" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-500" minOccurs="0"/>
 *         &lt;element userName="npaInfo" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-500" minOccurs="0"/>
 *         &lt;element userName="personInfo" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-500" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRequestedData", namespace = "urn://egisso-ru/types/prsn-request/1.0.3", propOrder = {
    "snils",
    "onmszCode",
    "assignmentsInclude",
    "assignmentsFilter",
    "obligationsInclude",
    "obligationsFilter",
    "incomesInclude",
    "assigneeInclude",
    "reportPeriod",
    "serviceTitle",
    "npaInfo",
    "personInfo"
})
@Builder
@Data
public class TRequestedData {

    @XmlElement(required = true)
    protected String snils;
    protected String onmszCode;
    protected boolean assignmentsInclude;
    protected TRequestedData.AssignmentsFilter assignmentsFilter;
    protected boolean obligationsInclude;
    protected TRequestedData.ObligationsFilter obligationsFilter;
    protected boolean incomesInclude;
    protected boolean assigneeInclude;
    @XmlElement(required = true)
    protected TRequestedData.ReportPeriod reportPeriod;
    protected String serviceTitle;
    protected String npaInfo;
    protected String personInfo;

    public TRequestedData() {
    }

    public TRequestedData(String snils, String onmszCode, boolean assignmentsInclude, AssignmentsFilter assignmentsFilter, boolean obligationsInclude, ObligationsFilter obligationsFilter, boolean incomesInclude, boolean assigneeInclude, ReportPeriod reportPeriod, String serviceTitle, String npaInfo, String personInfo) {
        this.snils = snils;
        this.onmszCode = onmszCode;
        this.assignmentsInclude = assignmentsInclude;
        this.assignmentsFilter = assignmentsFilter;
        this.obligationsInclude = obligationsInclude;
        this.obligationsFilter = obligationsFilter;
        this.incomesInclude = incomesInclude;
        this.assigneeInclude = assigneeInclude;
        this.reportPeriod = reportPeriod;
        this.serviceTitle = serviceTitle;
        this.npaInfo = npaInfo;
        this.personInfo = personInfo;
    }

    /**
     * Gets the value of the snils property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSnils() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSnils(String value) {
        this.snils = value;
    }

    /**
     * Gets the value of the onmszCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOnmszCode() {
        return onmszCode;
    }

    /**
     * Sets the value of the onmszCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOnmszCode(String value) {
        this.onmszCode = value;
    }

    /**
     * Gets the value of the assignmentsInclude property.
     *
     */
    public boolean isAssignmentsInclude() {
        return assignmentsInclude;
    }

    /**
     * Sets the value of the assignmentsInclude property.
     *
     */
    public void setAssignmentsInclude(boolean value) {
        this.assignmentsInclude = value;
    }

    /**
     * Gets the value of the assignmentsFilter property.
     *
     * @return
     *     possible object is
     *     {@link TRequestedData.AssignmentsFilter }
     *
     */
    public TRequestedData.AssignmentsFilter getAssignmentsFilter() {
        return assignmentsFilter;
    }

    /**
     * Sets the value of the assignmentsFilter property.
     *
     * @param value
     *     allowed object is
     *     {@link TRequestedData.AssignmentsFilter }
     *
     */
    public void setAssignmentsFilter(TRequestedData.AssignmentsFilter value) {
        this.assignmentsFilter = value;
    }

    /**
     * Gets the value of the obligationsInclude property.
     *
     */
    public boolean isObligationsInclude() {
        return obligationsInclude;
    }

    /**
     * Sets the value of the obligationsInclude property.
     *
     */
    public void setObligationsInclude(boolean value) {
        this.obligationsInclude = value;
    }

    /**
     * Gets the value of the obligationsFilter property.
     *
     * @return
     *     possible object is
     *     {@link TRequestedData.ObligationsFilter }
     *
     */
    public TRequestedData.ObligationsFilter getObligationsFilter() {
        return obligationsFilter;
    }

    /**
     * Sets the value of the obligationsFilter property.
     *
     * @param value
     *     allowed object is
     *     {@link TRequestedData.ObligationsFilter }
     *
     */
    public void setObligationsFilter(TRequestedData.ObligationsFilter value) {
        this.obligationsFilter = value;
    }

    /**
     * Gets the value of the incomesInclude property.
     *
     */
    public boolean isIncomesInclude() {
        return incomesInclude;
    }

    /**
     * Sets the value of the incomesInclude property.
     *
     */
    public void setIncomesInclude(boolean value) {
        this.incomesInclude = value;
    }

    /**
     * Gets the value of the assigneeInclude property.
     *
     */
    public boolean isAssigneeInclude() {
        return assigneeInclude;
    }

    /**
     * Sets the value of the assigneeInclude property.
     *
     */
    public void setAssigneeInclude(boolean value) {
        this.assigneeInclude = value;
    }

    /**
     * Gets the value of the reportPeriod property.
     *
     * @return
     *     possible object is
     *     {@link TRequestedData.ReportPeriod }
     *
     */
    public TRequestedData.ReportPeriod getReportPeriod() {
        return reportPeriod;
    }

    /**
     * Sets the value of the reportPeriod property.
     *
     * @param value
     *     allowed object is
     *     {@link TRequestedData.ReportPeriod }
     *
     */
    public void setReportPeriod(TRequestedData.ReportPeriod value) {
        this.reportPeriod = value;
    }

    /**
     * Gets the value of the serviceTitle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getServiceTitle() {
        return serviceTitle;
    }

    /**
     * Sets the value of the serviceTitle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setServiceTitle(String value) {
        this.serviceTitle = value;
    }

    /**
     * Gets the value of the npaInfo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNpaInfo() {
        return npaInfo;
    }

    /**
     * Sets the value of the npaInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNpaInfo(String value) {
        this.npaInfo = value;
    }

    /**
     * Gets the value of the personInfo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPersonInfo() {
        return personInfo;
    }

    /**
     * Sets the value of the personInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPersonInfo(String value) {
        this.personInfo = value;
    }


    /**
     *
     *               ��� ������: �������������� ��������� ��� ������ ����������
     *
     *
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element userName="form" type="{urn://egisso-ru/types/basic/1.0.6}tFormOfGranting" minOccurs="0"/>
     *         &lt;element userName="mszCodes" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}digits-4" maxOccurs="250" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "form",
        "mszCodes"
    })
    @Builder
    @Data
    public static class AssignmentsFilter {

        @XmlElement(namespace = "urn://egisso-ru/types/prsn-request/1.0.3")
        protected String form;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-request/1.0.3")
        protected List<String> mszCodes;

        public AssignmentsFilter() {
        }

        public AssignmentsFilter(String form, List<String> mszCodes) {
            this.form = form;
            this.mszCodes = mszCodes;
        }

        public List<String> getMszCodes() {
            if (mszCodes == null) {
                mszCodes = new ArrayList<String>();
            }
            return this.mszCodes;
        }

    }


    /**
     *
     *               ��� ������: �������������� ��������� ������������
     *
     *
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element userName="mszCodes" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}digits-4" maxOccurs="250" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mszCodes"
    })
    public static class ObligationsFilter {

        @XmlElement(namespace = "urn://egisso-ru/types/prsn-request/1.0.3")
        protected List<String> mszCodes;

        /**
         * Gets the value of the mszCodes property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mszCodes property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMszCodes().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         *
         *
         */
        public List<String> getMszCodes() {
            if (mszCodes == null) {
                mszCodes = new ArrayList<String>();
            }
            return this.mszCodes;
        }

    }


    /**
     *
     *                    Тип данных: Дополнительные параметры для фактов назначения
     *
     *
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element userName="beginDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element userName="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "beginDate",
        "endDate"
    })
    @Builder
    public static class ReportPeriod {

        @XmlElement(namespace = "urn://egisso-ru/types/prsn-request/1.0.3", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar beginDate;
        @XmlElement(namespace = "urn://egisso-ru/types/prsn-request/1.0.3", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endDate;


        public ReportPeriod() {
        }

        public ReportPeriod(XMLGregorianCalendar beginDate, XMLGregorianCalendar endDate) {
            this.beginDate = beginDate;
            this.endDate = endDate;
        }

        /**
         * Gets the value of the beginDate property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getBeginDate() {
            return beginDate;
        }

        /**
         * Sets the value of the beginDate property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setBeginDate(XMLGregorianCalendar value) {
            this.beginDate = value;
        }

        /**
         * Gets the value of the endDate property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

    }

}
