 package smev.ElementServices.Other;



import org.w3c.dom.Element;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "BusinessProcessMetadata", propOrder = {"any"})
 public class BusinessProcessMetadata
 {
   @XmlAnyElement
   protected List<Element> any;

   public List<Element> getAny() {
/* 64 */     if (this.any == null) {
/* 65 */       this.any = new ArrayList<>();
     }
/* 67 */     return this.any;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\BusinessProcessMetadata.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
