 package smev.ElementServices.Other;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "CreateGroupIdentity", propOrder = {"frguServiceCode", "frguServiceDescription", "frguServiceRecipientDescription"})
 public class CreateGroupIdentity
 {
   @XmlElement(name = "FRGUServiceCode", required = true)
   protected String frguServiceCode;
   @XmlElement(name = "FRGUServiceDescription")
   protected String frguServiceDescription;
   @XmlElement(name = "FRGUServiceRecipientDescription")
   protected String frguServiceRecipientDescription;

   public String getFRGUServiceCode() {
/*  55 */     return this.frguServiceCode;
   }









   public void setFRGUServiceCode(String value) {
/*  67 */     this.frguServiceCode = value;
   }









   public String getFRGUServiceDescription() {
/*  79 */     return this.frguServiceDescription;
   }









   public void setFRGUServiceDescription(String value) {
/*  91 */     this.frguServiceDescription = value;
   }









   public String getFRGUServiceRecipientDescription() {
/* 103 */     return this.frguServiceRecipientDescription;
   }









   public void setFRGUServiceRecipientDescription(String value) {
/* 115 */     this.frguServiceRecipientDescription = value;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\CreateGroupIdentity.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
