 package smev.ElementServices.Other;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "DynamicRoutingType", propOrder = {"dynamicValue"})
 public class DynamicRoutingType
 {
   @XmlElement(name = "DynamicValue", required = true)
   protected List<String> dynamicValue;

   public List<String> getDynamicValue() {
/* 63 */     if (this.dynamicValue == null) {
/* 64 */       this.dynamicValue = new ArrayList<>();
     }
/* 66 */     return this.dynamicValue;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\DynamicRoutingType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
