 package smev.ElementServices.Other;



import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

 @XmlType(name = "ErrorType")
 @XmlEnum
 public enum ErrorType
 {
  SERVER,
  CLIENT;

   public String value() {
/* 45 */     return name();
   }

   public static ErrorType fromValue(String v) {
/* 49 */     return valueOf(v);
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\ErrorType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
