 package smev.ElementServices.Other;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "IdentifierRoutingType", propOrder = {"identifierValue"})
 public class IdentifierRoutingType
 {
   @XmlElement(name = "IdentifierValue", required = true)
   protected List<String> identifierValue;

   public List<String> getIdentifierValue() {
/* 63 */     if (this.identifierValue == null) {
/* 64 */       this.identifierValue = new ArrayList<>();
     }
/* 66 */     return this.identifierValue;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\IdentifierRoutingType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
