 package smev.ElementServices.Other;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "LinkedGroupIdentity", propOrder = {"refClientId", "refGroupId"})
 public class LinkedGroupIdentity
 {
   protected String refClientId;
   protected String refGroupId;

   public String getRefClientId() {
/* 48 */     return this.refClientId;
   }









   public void setRefClientId(String value) {
/* 60 */     this.refClientId = value;
   }









   public String getRefGroupId() {
/* 72 */     return this.refGroupId;
   }









   public void setRefGroupId(String value) {
/* 84 */     this.refGroupId = value;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\LinkedGroupIdentity.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
