
package smev.ElementServices.Other;


import smev.ElementServices.fault.Fault;

import javax.xml.bind.annotation.XmlRegistry;


@XmlRegistry
public class ObjectFactory {


//    private static final QName _ClientMessage_QNAME = new QName("urn://x-artefacts-smev-gov-ru/services/service-adapter/types", "ClientMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.voskhod.smev.server.autogenerated.types.v1_2
     */
    public ObjectFactory() {
    }

//    public Response createResponse() {
//        return new Response();
//    }
//    public SnilsByAdditionalDataResponse createSnilsByAdditionalDataResponse() {
//        return new SnilsByAdditionalDataResponse();
//    }

//    public SnilsByAdditionalDataRequest createSnilsByAdditionalDataRequest() {
//        return new SnilsByAdditionalDataRequest();
//    }

    //    public Request createRequest() {
//        return new Request();
//    }
    public ClientMessage createClientMessage() {
        return new ClientMessage();
    }

//    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types", userName = "ClientMessage")
//    public JAXBElement<ClientMessage> createClientMessage(ClientMessage value) {
//        return new JAXBElement<>(_ClientMessage_QNAME, ClientMessage.class, null, value);
//    }

    public QueryResult createQueryResult() {
        return new QueryResult();
    }

    //обязательно, иначе QueryResult содержит только аттрибут messageType
    public RequestMessageType createRequestMessageType() {
        return new RequestMessageType();
    }

    //обязательно, иначе QueryResult содержит только аттрибут messageType
    public ResponseMessageType createResponseMessageType() {
        return new ResponseMessageType();
    }


    public Fault createFault() {
        return new Fault();
    }
//
//    public Content createContent() {
//        return new Content();
//    }
//
//    public ru.uszn.smev.ElementServices.infoEgissoBySnils.Request createRequest2() {
//        return new ru.uszn.smev.ElementServices.infoEgissoBySnils.Request();
//    }
//
//    public DOHFLNARequest createDOHFLNARequest() {
//        return new DOHFLNARequest();
//    }

//    public DOHFLNAResponse createDOHFLNAResponse() {
//        return new DOHFLNAResponse();
//    }

//
//    public RequestContent createRequestContent() {
//        return new RequestContent();
//    }

}
