
@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,

        xmlns = {
                @XmlNs(prefix="tns1", namespaceURI="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")

        }
)

        /*
        * добавил выше написанное чтобы успешно проходил unмаршалинг
        * QueryResult который идет с namespaces в корне QueryResult
        * Без этого кода он ругатся что xmlns неожиданный элемент
        * */


package smev.ElementServices.Other;



/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\package-info.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */

import javax.xml.bind.annotation.XmlNs;
