 package smev.ElementServices.Other;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "RegistryRoutingType", propOrder = {"registryRecordRouting"})
 public class RegistryRoutingType
 {
   @XmlElement(name = "RegistryRecordRouting", required = true)
   protected List<RegistryRecordRoutingType> registryRecordRouting;

   public List<RegistryRecordRoutingType> getRegistryRecordRouting() {
/* 63 */     if (this.registryRecordRouting == null) {
/* 64 */       this.registryRecordRouting = new ArrayList<>();
     }
/* 66 */     return this.registryRecordRouting;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\RegistryRoutingType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
