 package smev.ElementServices.Other;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "RegistryRecordRoutingType", propOrder = {"recordId", "useGeneralRouting", "dynamicRouting", "identifierRouting"})
 public class RegistryRecordRoutingType
 {
   @XmlElement(name = "RecordId")
   protected int recordId;
   @XmlElement(name = "UseGeneralRouting")
   protected boolean useGeneralRouting;
   @XmlElement(name = "DynamicRouting")
   protected DynamicRoutingType dynamicRouting;
   @XmlElement(name = "IdentifierRouting")
   protected IdentifierRoutingType identifierRouting;

   public int getRecordId() {
/*  55 */     return this.recordId;
   }





   public void setRecordId(int value) {
/*  63 */     this.recordId = value;
   }





   public boolean isUseGeneralRouting() {
/*  71 */     return this.useGeneralRouting;
   }





   public void setUseGeneralRouting(boolean value) {
/*  79 */     this.useGeneralRouting = value;
   }









   public DynamicRoutingType getDynamicRouting() {
/*  91 */     return this.dynamicRouting;
   }









   public void setDynamicRouting(DynamicRoutingType value) {
/* 103 */     this.dynamicRouting = value;
   }









   public IdentifierRoutingType getIdentifierRouting() {
/* 115 */     return this.identifierRouting;
   }









   public void setIdentifierRouting(IdentifierRoutingType value) {
/* 127 */     this.identifierRouting = value;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\RegistryRecordRoutingType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
