//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.05.22 at 01:32:40 PM KRAT
//


package smev.ElementServices.Other;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RejectCode.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType userName="RejectCode">
 *   &lt;restriction base="{urn://x-artefacts-smev-gov-ru/services/service-adapter/types}string-50">
 *     &lt;enumeration value="ACCESS_DENIED"/>
 *     &lt;enumeration value="NO_DATA"/>
 *     &lt;enumeration value="UNKNOWN_REQUEST_DESCRIPTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "RejectCode")
@XmlEnum
public enum RejectCode {

    ACCESS_DENIED,

    NO_DATA,

    FAILURE,

    UNKNOWN_REQUEST_DESCRIPTION;

    public String value() {
        return name();
    }

    public static RejectCode fromValue(String v) {
        return valueOf(v);
    }

}
