 package smev.ElementServices.Other;

 import lombok.Data;

 import javax.xml.bind.annotation.*;
 import javax.xml.datatype.XMLGregorianCalendar;

 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "RequestMetadataType", propOrder = {"linkedGroupIdentity", "createGroupIdentity", "nodeId", "eol", "testMessage", "transactionCode", "businessProcessMetadata", "routingInformation"})
 @Data
 public class RequestMetadataType
   extends Metadata
 {
   protected LinkedGroupIdentity linkedGroupIdentity;
   protected CreateGroupIdentity createGroupIdentity;
   protected String nodeId;
   @XmlSchemaType(name = "dateTime")
   protected XMLGregorianCalendar eol;
   protected Boolean testMessage;
   @XmlElement(name = "TransactionCode")
   protected String transactionCode;
   @XmlElement(name = "BusinessProcessMetadata")
   protected BusinessProcessMetadata businessProcessMetadata;
   @XmlElement(name = "RoutingInformation")
   protected RoutingInformationType routingInformation;

   public LinkedGroupIdentity getLinkedGroupIdentity() {
    return this.linkedGroupIdentity;
   }









   public void setLinkedGroupIdentity(LinkedGroupIdentity value) {
/*  89 */     this.linkedGroupIdentity = value;
   }









   public CreateGroupIdentity getCreateGroupIdentity() {
/* 101 */     return this.createGroupIdentity;
   }









   public void setCreateGroupIdentity(CreateGroupIdentity value) {
/* 113 */     this.createGroupIdentity = value;
   }









   public String getNodeId() {
/* 125 */     return this.nodeId;
   }









   public void setNodeId(String value) {
/* 137 */     this.nodeId = value;
   }









   public XMLGregorianCalendar getEol() {
/* 149 */     return this.eol;
   }









   public void setEol(XMLGregorianCalendar value) {
/* 161 */     this.eol = value;
   }









   public Boolean isTestMessage() {
/* 173 */     return this.testMessage;
   }









   public void setTestMessage(Boolean value) {
/* 185 */     this.testMessage = value;
   }









   public String getTransactionCode() {
/* 197 */     return this.transactionCode;
   }









   public void setTransactionCode(String value) {
/* 209 */     this.transactionCode = value;
   }









   public BusinessProcessMetadata getBusinessProcessMetadata() {
/* 221 */     return this.businessProcessMetadata;
   }









   public void setBusinessProcessMetadata(BusinessProcessMetadata value) {
/* 233 */     this.businessProcessMetadata = value;
   }









   public RoutingInformationType getRoutingInformation() {
/* 245 */     return this.routingInformation;
   }









   public void setRoutingInformation(RoutingInformationType value) {
/* 257 */     this.routingInformation = value;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\RequestMetadataType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
