 package smev.ElementServices.Other;



import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "ResponseMessageType", propOrder = {"responseMetadata", "responseContent"})
 @Data
 public class ResponseMessageType
   extends Message
 {
   @XmlElement(name = "ResponseMetadata", required = true)
   protected ResponseMetadataType responseMetadata;
   @XmlElement(name = "ResponseContent", required = true)
   protected ResponseContentType responseContent;

 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\ResponseMessageType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
