 package smev.ElementServices.Other;



import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "ResponseMetadataType", propOrder = {"replyToClientId"})
 @Data
 public class ResponseMetadataType
   extends Metadata
 {
   @XmlElement(required = true)
   protected String replyToClientId;


   public String getReplyToClientId() {
/* 49 */     return this.replyToClientId;
   }









   public void setReplyToClientId(String value) {
/* 61 */     this.replyToClientId = value;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\ResponseMetadataType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
