 package smev.ElementServices.Other;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "RoutingInformationType", propOrder = {"dynamicRouting", "identifierRouting", "registryRouting"})
 public class RoutingInformationType
 {
   @XmlElement(name = "DynamicRouting")
   protected DynamicRoutingType dynamicRouting;
   @XmlElement(name = "IdentifierRouting")
   protected IdentifierRoutingType identifierRouting;
   @XmlElement(name = "RegistryRouting")
   protected RegistryRoutingType registryRouting;

   public DynamicRoutingType getDynamicRouting() {
/*  55 */     return this.dynamicRouting;
   }









   public void setDynamicRouting(DynamicRoutingType value) {
/*  67 */     this.dynamicRouting = value;
   }









   public IdentifierRoutingType getIdentifierRouting() {
/*  79 */     return this.identifierRouting;
   }









   public void setIdentifierRouting(IdentifierRoutingType value) {
/*  91 */     this.identifierRouting = value;
   }









   public RegistryRoutingType getRegistryRouting() {
/* 103 */     return this.registryRouting;
   }









   public void setRegistryRouting(RegistryRoutingType value) {
/* 115 */     this.registryRouting = value;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\RoutingInformationType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
