 package smev.ElementServices.Other;



import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;

 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "StatusMessage", propOrder = {"statusMetadata", "status", "details", "timestamp"})
 public class StatusMessage
   extends Message
 {
   @XmlElement(required = true)
   protected StatusMetadataType statusMetadata;
   @XmlElement(required = true)
   protected StatusMessageCategory status;
   protected String details;
   @XmlSchemaType(name = "dateTime")
   protected XMLGregorianCalendar timestamp;

   public StatusMetadataType getStatusMetadata() {
/*  62 */     return this.statusMetadata;
   }









   public void setStatusMetadata(StatusMetadataType value) {
/*  74 */     this.statusMetadata = value;
   }









   public StatusMessageCategory getStatus() {
/*  86 */     return this.status;
   }









   public void setStatus(StatusMessageCategory value) {
/*  98 */     this.status = value;
   }









   public String getDetails() {
/* 110 */     return this.details;
   }









   public void setDetails(String value) {
/* 122 */     this.details = value;
   }









   public XMLGregorianCalendar getTimestamp() {
/* 134 */     return this.timestamp;
   }









   public void setTimestamp(XMLGregorianCalendar value) {
/* 146 */     this.timestamp = value;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\StatusMessage.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
