 package smev.ElementServices.Other;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "StatusMetadataType", propOrder = {"originalClientId"})
 public class StatusMetadataType
   extends Metadata
 {
   @XmlElement(required = true)
   protected String originalClientId;

   public String getOriginalClientId() {
/* 49 */     return this.originalClientId;
   }









   public void setOriginalClientId(String value) {
/* 61 */     this.originalClientId = value;
   }
 }


/* Location:              F:\Java_project\01_work\01 temp\smev-adapter\BOOT-INF\lib\3.1.7\schema-3.1.7.jar!\ru\voskhod\smev\adapter\autogenerated\types\StatusMetadataType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */
