//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.30 at 11:38:56 PM MSK
//


package smev.ElementServices.Mvd2;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * �����
 *
 * <p>Java class for Address complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="regionOktmo" type="{urn://mvd/guvm/basic-types/1.2.0}String125" minOccurs="0"/>
 *         &lt;element name="district" type="{urn://mvd/guvm/basic-types/1.2.0}String500" minOccurs="0"/>
 *         &lt;element name="settlement" type="{urn://mvd/guvm/basic-types/1.2.0}String125" minOccurs="0"/>
 *         &lt;element name="street" type="{urn://mvd/guvm/basic-types/1.2.0}String125" minOccurs="0"/>
 *         &lt;element name="house" type="{urn://mvd/guvm/basic-types/1.2.0}String25" minOccurs="0"/>
 *         &lt;element name="building" type="{urn://mvd/guvm/basic-types/1.2.0}String25" minOccurs="0"/>
 *         &lt;element name="flat" type="{urn://mvd/guvm/basic-types/1.2.0}String25" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", propOrder = {
    "regionOktmo",
    "district",
    "settlement",
    "street",
    "house",
    "building",
    "flat"
})
@XmlSeeAlso({
    RegistrationInfo2 .class
})
@Data
public class Address {

    protected String regionOktmo;
    protected String district;
    protected String settlement;
    protected String street;
    protected String house;
    protected String building;
    protected String flat;

}
