//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.30 at 11:38:56 PM MSK
//


package smev.ElementServices.Mvd2;

import lombok.Data;
import smev.utils.LocalDateAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.time.LocalDate;


/**
 * ������������� � ��������
 *
 * <p>Java class for BirthCertificate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BirthCertificate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="series" type="{urn://mvd/guvm/basic-types/1.2.0}BirthCertificateSeries"/>
 *         &lt;element name="number" type="{urn://mvd/guvm/basic-types/1.2.0}Digits6"/>
 *         &lt;element name="issueDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BirthCertificate", namespace = "urn://mvd/guvm/basic-types/1.2.0", propOrder = {
    "series",
    "number",
    "issueDate"
})
@Data
public class BirthCertificate {

    @XmlElement(required = true)
    protected String series;
    @XmlElement(required = true)
    protected String number;
    @XmlElement(required = true)
    //@XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate issueDate;

}
