//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.30 at 11:38:56 PM MSK
//


package smev.ElementServices.Mvd2;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * ������ �����������
 *
 * <p>Java class for RegistrationInfo2 complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RegistrationInfo2">
 *   &lt;complexContent>
 *     &lt;extension base="{urn://mvd/guvm/registration-commons/1.2.0}Address">
 *       &lt;sequence>
 *         &lt;element name="region" type="{urn://mvd/guvm/basic-types/1.2.0}String125" minOccurs="0"/>
 *         &lt;element name="registrationDateFrom" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="unstructuredAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistrationInfo2", propOrder = {
    "region",
    "registrationDateFrom",
    "unstructuredAddress"
})
@XmlSeeAlso({
    RegistrationInfo.class
})
@Data
public class RegistrationInfo2
    extends Address
{

    protected String region;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar registrationDateFrom;
    protected String unstructuredAddress;

}
