//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.30 at 11:38:56 PM MSK
//


package smev.ElementServices.Mvd2;

import smev.utils.LocalDateAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.time.LocalDate;


/**
 *
 *                 ������ �������� ���������� ��: �����, �����, ���� ������
 *
 *
 * <p>Java class for RussianPassport complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RussianPassport">
 *   &lt;complexContent>
 *     &lt;extension base="{urn://mvd/guvm/basic-types/1.2.0}RussianPassportBase">
 *       &lt;sequence>
 *         &lt;element name="issueDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RussianPassport", namespace = "urn://mvd/guvm/basic-types/1.2.0", propOrder = {
    "issueDate"
})
public class RussianPassport
    extends RussianPassportBase
{

    @XmlElement(required = true, namespace = "urn://mvd/guvm/basic-types/1.2.0")
    //@XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate issueDate;

    /**
     * Gets the value of the issueDate property.
     *
     * @return
     *     possible object is
     *     {@link LocalDate }
     *
     */
    public LocalDate getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     *
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *
     */
    public void setIssueDate(LocalDate value) {
        this.issueDate = value;
    }

}
