//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.17 at 10:36:59 PM AMT
//


package smev.ElementServices.Kmsz;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *
 *         ��� ������: ������� ����������� ������������� �������������� ���
 *
 *
 * <p>Java class for tPeriodicityPosition complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType userName="tPeriodicityPosition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element userName="code" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}digits-2"/>
 *         &lt;element userName="title" type="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}string-100"/>
 *         &lt;element userName="start_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element userName="finish_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPeriodicityPosition", namespace = "urn://egisso-ru/types/cls-periodicity/1.0.0", propOrder = {
    "code",
    "title",
    "startDate",
    "finishDate"
})
public class TPeriodicityPosition {

    @XmlElement(namespace = "urn://egisso-ru/types/cls-periodicity/1.0.0", required = true)
    protected String code;
    @XmlElement(namespace = "urn://egisso-ru/types/cls-periodicity/1.0.0", required = true)
    protected String title;
    @XmlElement(name = "start_date", namespace = "urn://egisso-ru/types/cls-periodicity/1.0.0", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "finish_date", namespace = "urn://egisso-ru/types/cls-periodicity/1.0.0")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar finishDate;

    /**
     * Gets the value of the code property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the startDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the finishDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFinishDate() {
        return finishDate;
    }

    /**
     * Sets the value of the finishDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setFinishDate(XMLGregorianCalendar value) {
        this.finishDate = value;
    }

}
