//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.10.09 at 12:02:18 AM MSK
//


package smev.ElementServices.Mvd;

import com.fasterxml.jackson.annotation.JsonInclude;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ ���������: ���, �����, �����, ���� ������
 *
 * <p>Java class for DocumentInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DocumentInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="russianPassport" type="{urn://mvd/guvm/basic-types/1.2.0}RussianPassport"/>
 *         &lt;element name="foreignPassport" type="{urn://mvd/guvm/basic-types/1.2.0}ForeignPassport"/>
 *         &lt;element name="birthCertificate" type="{urn://mvd/guvm/basic-types/1.2.0}BirthCertificate"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentInfo", propOrder = {
    "russianPassport",
    "foreignPassport",
    "birthCertificate"
})
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DocumentInfo {

    protected RussianPassport russianPassport;
    protected ForeignPassport foreignPassport;
    protected BirthCertificate birthCertificate;

    /**
     * Gets the value of the russianPassport property.
     *
     * @return
     *     possible object is
     *     {@link RussianPassport }
     *
     */
    public RussianPassport getRussianPassport() {
        return russianPassport;
    }

    /**
     * Sets the value of the russianPassport property.
     *
     * @param value
     *     allowed object is
     *     {@link RussianPassport }
     *
     */
    public void setRussianPassport(RussianPassport value) {
        this.russianPassport = value;
    }

    /**
     * Gets the value of the foreignPassport property.
     *
     * @return
     *     possible object is
     *     {@link ForeignPassport }
     *
     */
    public ForeignPassport getForeignPassport() {
        return foreignPassport;
    }

    /**
     * Sets the value of the foreignPassport property.
     *
     * @param value
     *     allowed object is
     *     {@link ForeignPassport }
     *
     */
    public void setForeignPassport(ForeignPassport value) {
        this.foreignPassport = value;
    }

    /**
     * Gets the value of the birthCertificate property.
     *
     * @return
     *     possible object is
     *     {@link BirthCertificate }
     *
     */
    public BirthCertificate getBirthCertificate() {
        return birthCertificate;
    }

    /**
     * Sets the value of the birthCertificate property.
     *
     * @param value
     *     allowed object is
     *     {@link BirthCertificate }
     *
     */
    public void setBirthCertificate(BirthCertificate value) {
        this.birthCertificate = value;
    }

}
