//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.10.09 at 12:02:18 AM MSK
//


package smev.ElementServices.Mvd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="registrationInfo" type="{urn://mvd/guvm/registration-commons/1.2.0}RegistrationInfo"/>
 *         &lt;element name="notFoundRegistration" type="{urn://mvd/guvm/registration-commons/1.2.0}NotFoundRegistration"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "registrationInfo",
    "notFoundRegistration"
})
@XmlRootElement(name = "livingPlaceRegistrationResponse", namespace = "urn://mvd/guvm/living-place-registration/1.1.0")
public class LivingPlaceRegistrationResponse {

    @XmlElement(namespace = "urn://mvd/guvm/living-place-registration/1.1.0")
    protected RegistrationInfo registrationInfo;
    @XmlElement(namespace = "urn://mvd/guvm/living-place-registration/1.1.0")
    protected NotFoundRegistration notFoundRegistration;

    /**
     * Gets the value of the registrationInfo property.
     *
     * @return
     *     possible object is
     *     {@link RegistrationInfo }
     *
     */
    public RegistrationInfo getRegistrationInfo() {
        return registrationInfo;
    }

    /**
     * Sets the value of the registrationInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link RegistrationInfo }
     *
     */
    public void setRegistrationInfo(RegistrationInfo value) {
        this.registrationInfo = value;
    }

    /**
     * Gets the value of the notFoundRegistration property.
     *
     * @return
     *     possible object is
     *     {@link NotFoundRegistration }
     *
     */
    public NotFoundRegistration getNotFoundRegistration() {
        return notFoundRegistration;
    }

    /**
     * Sets the value of the notFoundRegistration property.
     *
     * @param value
     *     allowed object is
     *     {@link NotFoundRegistration }
     *
     */
    public void setNotFoundRegistration(NotFoundRegistration value) {
        this.notFoundRegistration = value;
    }

}
