//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.10.09 at 12:02:18 AM MSK
//


package smev.ElementServices.Mvd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.time.LocalDate;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the mypack package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

//    private final static QName _LivingPlaceRegistrationRequest_QNAME = new QName("urn://mvd/guvm/living-place-registration/1.1.0", "livingPlaceRegistrationRequest");
//    private final static QName _RussianPassport_QNAME = new QName("urn://mvd/guvm/basic-types/1.2.0", "russianPassport");
//    private final static QName _BirthCertificate_QNAME = new QName("urn://mvd/guvm/basic-types/1.2.0", "birthCertificate");
//    private final static QName _ForeignPassport_QNAME = new QName("urn://mvd/guvm/basic-types/1.2.0", "foreignPassport");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mypack
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistrationRequest }
     *
     */
    public RegistrationRequest createRegistrationRequest() {
        return new RegistrationRequest();
    }

    /**
     * Create an instance of {@link LivingPlaceRegistrationResponse }
     *
     */
    public LivingPlaceRegistrationResponse createLivingPlaceRegistrationResponse() {
        return new LivingPlaceRegistrationResponse();
    }

    /**
     * Create an instance of {@link RegistrationInfo }
     *
     */
    public RegistrationInfo createRegistrationInfo() {
        return new RegistrationInfo();
    }

    /**
     * Create an instance of {@link NotFoundRegistration }
     *
     */
    public NotFoundRegistration createNotFoundRegistration() {
        return new NotFoundRegistration();
    }

    /**
     * Create an instance of {@link RegistrationValidityResponse }
     *
     */
    public RegistrationValidityResponse createRegistrationValidityResponse() {
        return new RegistrationValidityResponse();
    }

    /**
     * Create an instance of {@link ValidRegistration }
     *
     */
    public ValidRegistration createValidRegistration() {
        return new ValidRegistration();
    }

    /**
     * Create an instance of {@link Address }
     *
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link RegistrationValidityRequest }
     *
     */
    public RegistrationValidityRequest createRegistrationValidityRequest() {
        return new RegistrationValidityRequest();
    }

    /**
     * Create an instance of {@link InvalidRegistration }
     *
     */
    public InvalidRegistration createInvalidRegistration() {
        return new InvalidRegistration();
    }

    /**
     * Create an instance of {@link DocumentInfo }
     *
     */
    public DocumentInfo createDocumentInfo() {
        return new DocumentInfo();
    }

    /**
     * Create an instance of {@link RussianPassport }
     *
     */
    public RussianPassport createRussianPassport() {
        return new RussianPassport();
    }

    /**
     * Create an instance of {@link ForeignPassport }
     *
     */
    public ForeignPassport createForeignPassport() {
        return new ForeignPassport();
    }

    /**
     * Create an instance of {@link BirthCertificate }
     *
     */
    public BirthCertificate createBirthCertificate() {
        return new BirthCertificate();
    }

    /**
     * Create an instance of {@link RussianPassportBase }
     *
     */
    public RussianPassportBase createRussianPassportBase() {
        return new RussianPassportBase();
    }

    /**
     * Create an instance of {@link PersonInfoBase }
     *
     */
    public PersonInfoBase createPersonInfoBase() {
        return new PersonInfoBase();
    }

    /**
     * Create an instance of {@link PersonInfo }
     *
     */
    public PersonInfo createPersonInfo() {
        return new PersonInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistrationRequest }{@code >}}
     *
     */
//    @XmlElementDecl(namespace = "urn://mvd/guvm/living-place-registration/1.1.0", name = "livingPlaceRegistrationRequest")
//    public JAXBElement<RegistrationRequest> createLivingPlaceRegistrationRequest(RegistrationRequest value) {
//        return new JAXBElement<RegistrationRequest>(_LivingPlaceRegistrationRequest_QNAME, RegistrationRequest.class, null, value);
//    }

       /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RussianPassport }{@code >}}
     *
     */
//    @XmlElementDecl(namespace = "urn://mvd/guvm/basic-types/1.2.0", name = "russianPassport")
//    public JAXBElement<RussianPassport> createRussianPassport(RussianPassport value) {
//        return new JAXBElement<RussianPassport>(_RussianPassport_QNAME, RussianPassport.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link BirthCertificate }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://mvd/guvm/basic-types/1.2.0", name = "birthCertificate")
//    public JAXBElement<BirthCertificate> createBirthCertificate(BirthCertificate value) {
//        return new JAXBElement<BirthCertificate>(_BirthCertificate_QNAME, BirthCertificate.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link ForeignPassport }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "urn://mvd/guvm/basic-types/1.2.0", name = "foreignPassport")
//    public JAXBElement<ForeignPassport> createForeignPassport(ForeignPassport value) {
//        return new JAXBElement<ForeignPassport>(_ForeignPassport_QNAME, ForeignPassport.class, null, value);
//    }

}
