//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.10.09 at 12:02:18 AM MSK
//


package smev.ElementServices.Mvd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ��������� ������� �������� ���������������� �����������
 *
 * <p>Java class for RegistrationValidityRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RegistrationValidityRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{urn://mvd/guvm/registration-commons/1.2.0}RegistrationRequest">
 *       &lt;sequence>
 *         &lt;element name="registrationAddress" type="{urn://mvd/guvm/registration-commons/1.2.0}Address"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistrationValidityRequest", propOrder = {
    "registrationAddress"
})
public class RegistrationValidityRequest
    extends RegistrationRequest
{

    @XmlElement(required = true)
    protected Address registrationAddress;

    /**
     * Gets the value of the registrationAddress property.
     *
     * @return
     *     possible object is
     *     {@link Address }
     *
     */
    public Address getRegistrationAddress() {
        return registrationAddress;
    }

    /**
     * Sets the value of the registrationAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link Address }
     *
     */
    public void setRegistrationAddress(Address value) {
        this.registrationAddress = value;
    }

}
