//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.10.09 at 12:02:18 AM MSK
//


package smev.ElementServices.Mvd;

import lombok.Data;
import smev.utils.LocalDateAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDate;


/**
 * ������ �����������
 *
 * <p>Java class for RegistrationInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RegistrationInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{urn://mvd/guvm/registration-commons/1.2.0}Address">
 *       &lt;sequence>
 *         &lt;element name="region" type="{urn://mvd/guvm/basic-types/1.2.0}String125" minOccurs="0"/>
 *         &lt;element name="registrationDateFrom" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="unstructuredAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistrationInfo", propOrder = {
    "region",
    "registrationDateFrom",
    "unstructuredAddress"
})
@Data
public class RegistrationInfo
    extends Address
{

    protected String region;
    @XmlElement(required = true)
//    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate registrationDateFrom;
    protected String unstructuredAddress;

}
