//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.10.09 at 12:02:18 AM MSK
//


package smev.ElementServices.Mvd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ����� �� ������ �������� ���������������� �����������
 *
 * <p>Java class for RegistrationValidityResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RegistrationValidityResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="validRegistration" type="{urn://mvd/guvm/registration-commons/1.2.0}ValidRegistration"/>
 *           &lt;element name="invalidRegistration" type="{urn://mvd/guvm/registration-commons/1.2.0}InvalidRegistration"/>
 *           &lt;element name="notFoundRegistration" type="{urn://mvd/guvm/registration-commons/1.2.0}NotFoundRegistration"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistrationValidityResponse", propOrder = {
    "validRegistration",
    "invalidRegistration",
    "notFoundRegistration"
})
public class RegistrationValidityResponse {

    protected ValidRegistration validRegistration;
    protected InvalidRegistration invalidRegistration;
    protected NotFoundRegistration notFoundRegistration;

    /**
     * Gets the value of the validRegistration property.
     *
     * @return
     *     possible object is
     *     {@link ValidRegistration }
     *
     */
    public ValidRegistration getValidRegistration() {
        return validRegistration;
    }

    /**
     * Sets the value of the validRegistration property.
     *
     * @param value
     *     allowed object is
     *     {@link ValidRegistration }
     *
     */
    public void setValidRegistration(ValidRegistration value) {
        this.validRegistration = value;
    }

    /**
     * Gets the value of the invalidRegistration property.
     *
     * @return
     *     possible object is
     *     {@link InvalidRegistration }
     *
     */
    public InvalidRegistration getInvalidRegistration() {
        return invalidRegistration;
    }

    /**
     * Sets the value of the invalidRegistration property.
     *
     * @param value
     *     allowed object is
     *     {@link InvalidRegistration }
     *
     */
    public void setInvalidRegistration(InvalidRegistration value) {
        this.invalidRegistration = value;
    }

    /**
     * Gets the value of the notFoundRegistration property.
     *
     * @return
     *     possible object is
     *     {@link NotFoundRegistration }
     *
     */
    public NotFoundRegistration getNotFoundRegistration() {
        return notFoundRegistration;
    }

    /**
     * Sets the value of the notFoundRegistration property.
     *
     * @param value
     *     allowed object is
     *     {@link NotFoundRegistration }
     *
     */
    public void setNotFoundRegistration(NotFoundRegistration value) {
        this.notFoundRegistration = value;
    }

}
